import { LifeStage } from '@lifeverse/shared';
import type { GameEvent } from '@lifeverse/shared';

export const adolescenceEvents: GameEvent[] = [
  {
    id: 'ad_first_job',
    title: 'First Paycheck',
    description: 'A local shop is hiring after-school help. Your parents say it\'s your choice.',
    stages: [LifeStage.Adolescence],
    statConditions: [],
    flagConditions: [{ key: 'isEmployed', value: false }],
    weight: 2,
    cooldownYears: 99,
    choices: [
      {
        id: 'take_job',
        label: 'Take the job',
        statDeltas: [{ stat: 'discipline', amount: 4 }, { stat: 'intelligence', amount: -2 }, { stat: 'happiness', amount: 3 }],
        flagChanges: [{ key: 'hadPartTimeJob', value: true }],
        outcome: 'The first paycheck feels enormous even though it\'s not. You\'ve crossed a threshold.',
      },
      {
        id: 'focus_school',
        label: 'Focus on school instead',
        statDeltas: [{ stat: 'intelligence', amount: 4 }, { stat: 'discipline', amount: 2 }],
        flagChanges: [],
        outcome: 'Your grades climb. The money can wait.',
      },
    ],
  },
  {
    id: 'ad_peer_pressure',
    title: 'The Party',
    description: 'An older student invites you to a party. There will be drinking. The popular crowd will be there.',
    stages: [LifeStage.Adolescence],
    statConditions: [],
    flagConditions: [],
    weight: 2,
    cooldownYears: 4,
    choices: [
      {
        id: 'go_and_drink',
        label: 'Go and join in',
        statDeltas: [{ stat: 'charisma', amount: 4 }, { stat: 'health', amount: -3 }, { stat: 'happiness', amount: 3 }],
        flagChanges: [],
        outcome: 'You fit in for one night. It\'s thrilling and a little empty.',
        seedsThreads: [{
          key: 'risk_appetite_thread',
          category: 'personal',
          payload: { origin: 'teen_drinking' },
          triggerMinAge: 20,
          triggerMaxAge: 35,
        }],
      },
      {
        id: 'go_and_abstain',
        label: 'Go but don\'t drink',
        statDeltas: [{ stat: 'charisma', amount: 2 }, { stat: 'discipline', amount: 4 }, { stat: 'willpower', amount: 8 }],
        flagChanges: [],
        outcome: 'You make your own call in a room that rewards conformity. Some people respect that.',
      },
      {
        id: 'skip',
        label: 'Stay home',
        statDeltas: [{ stat: 'discipline', amount: 3 }, { stat: 'intelligence', amount: 3 }, { stat: 'charisma', amount: -2 }],
        flagChanges: [],
        outcome: 'You spend the night reading and wonder, briefly, if you made the right call.',
      },
    ],
  },
  {
    id: 'ad_first_romance',
    title: 'Something More',
    description: 'Someone in your class has been looking at you differently lately. Today they pass you a note.',
    stages: [LifeStage.Adolescence],
    statConditions: [],
    flagConditions: [{ key: 'hasPartner', value: false }],
    weight: 2,
    cooldownYears: 99,
    choices: [
      {
        id: 'pursue',
        label: 'Write back and ask them out',
        statDeltas: [{ stat: 'charisma', amount: 4 }, { stat: 'happiness', amount: 6 }],
        flagChanges: [{ key: 'hasPartner', value: true }],
        outcome: 'Your first relationship. Clumsy, earnest, and more important than you know at the time.',
        seedsThreads: [{
          key: 'first_love_thread',
          category: 'personal',
          payload: { origin: 'teen_romance' },
          triggerMinAge: 25,
          triggerMaxAge: 50,
        }],
      },
      {
        id: 'decline',
        label: 'Pretend you didn\'t get the note',
        statDeltas: [{ stat: 'happiness', amount: -2 }, { stat: 'discipline', amount: 2 }],
        flagChanges: [],
        outcome: 'You play it safe. You wonder about it for a while.',
      },
    ],
  },
  {
    id: 'ad_school_fight',
    title: 'The Hallway',
    description: 'A disagreement in the hallway escalates. Suddenly there\'s a circle of students around you.',
    stages: [LifeStage.Adolescence],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 5,
    choices: [
      {
        id: 'fight',
        label: 'Throw the first punch',
        statDeltas: [{ stat: 'health', amount: -4 }, { stat: 'charisma', amount: 3 }, { stat: 'discipline', amount: -3 }],
        flagChanges: [],
        outcome: 'You win the fight and a three-day suspension. Your parents are called.',
      },
      {
        id: 'deescalate',
        label: 'Step back and say something unexpected',
        statDeltas: [{ stat: 'charisma', amount: 5 }, { stat: 'intelligence', amount: 3 }, { stat: 'happiness', amount: 2 }],
        flagChanges: [],
        outcome: 'The crowd disperses confused. Someone calls you cool. You are not sure why that means so much.',
      },
    ],
  },
  {
    id: 'ad_mentor_teacher',
    title: 'Ms. Okafor',
    description: 'Your history teacher stays after class. She says: "You see things other students don\'t. That\'s rare."',
    stages: [LifeStage.Adolescence],
    statConditions: [{ stat: 'intelligence', operator: 'gte', value: 55 }],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'take_mentorship',
        label: 'Take her up on mentorship',
        statDeltas: [{ stat: 'intelligence', amount: 6 }, { stat: 'charisma', amount: 3 }, { stat: 'happiness', amount: 4 }],
        flagChanges: [{ key: 'hasMentor', value: true }],
        outcome: 'She lends you books nobody assigns and writes a college recommendation that opens doors.',
        seedsThreads: [{
          key: 'mentor_thread',
          category: 'career',
          payload: { mentorName: 'Ms. Okafor' },
          triggerMinAge: 22,
          triggerMaxAge: 40,
        }],
      },
      {
        id: 'polite_decline',
        label: 'Smile and move on',
        statDeltas: [{ stat: 'intelligence', amount: 2 }],
        flagChanges: [],
        outcome: 'A door closes quietly. You wonder sometimes what was behind it.',
      },
    ],
  },
  {
    id: 'ad_band_or_sport',
    title: 'Choose Your Tribe',
    description: 'You have to pick an extracurricular: the school band or the varsity sports team. Both have practice at the same time.',
    stages: [LifeStage.Adolescence],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'band',
        label: 'Join the band',
        statDeltas: [{ stat: 'creativity', amount: 5 }, { stat: 'charisma', amount: 3 }, { stat: 'discipline', amount: 3 }],
        flagChanges: [{ key: 'playsMusic', value: true }],
        outcome: 'You play your first gig at the school dance. The applause hits differently than any grade ever has.',
      },
      {
        id: 'sport',
        label: 'Join the sports team',
        statDeltas: [{ stat: 'health', amount: 5 }, { stat: 'discipline', amount: 5 }, { stat: 'charisma', amount: 3 }],
        flagChanges: [{ key: 'playsTeamSport', value: true }],
        outcome: 'Pre-dawn runs and weekend games build something in you that the classroom never could.',
      },
    ],
  },
  {
    id: 'ad_college_talk',
    title: 'The Decision',
    description: 'Your school counsellor calls you in. "It\'s time to think about what comes next," she says.',
    stages: [LifeStage.Adolescence],
    statConditions: [],
    flagConditions: [],
    weight: 2,
    cooldownYears: 99,
    choices: [
      {
        id: 'university_plan',
        label: 'Plan for university',
        statDeltas: [{ stat: 'intelligence', amount: 4 }, { stat: 'discipline', amount: 3 }],
        flagChanges: [{ key: 'planningUniversity', value: true }],
        outcome: 'You leave with a list of target schools and a growing stack of vocabulary flashcards.',
      },
      {
        id: 'trade_plan',
        label: 'Look into trade school',
        statDeltas: [{ stat: 'discipline', amount: 5 }, { stat: 'creativity', amount: 2 }],
        flagChanges: [{ key: 'planningTrade', value: true }],
        outcome: 'Practical skills, real-world demand, no debt spiral. Not every path runs through a campus.',
      },
      {
        id: 'no_plan',
        label: 'Say you\'ll figure it out',
        statDeltas: [{ stat: 'happiness', amount: 2 }, { stat: 'intelligence', amount: -2 }],
        flagChanges: [],
        outcome: 'The counsellor tries not to look worried. You appreciate the effort.',
      },
    ],
  },
  {
    id: 'ad_family_trouble',
    title: 'The Bills',
    description: 'You overhear your parents: there are money problems. Your father works a second job now. The house feels quieter.',
    stages: [LifeStage.Adolescence],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'get_a_job',
        label: 'Find work to help the family',
        statDeltas: [{ stat: 'discipline', amount: 5 }, { stat: 'intelligence', amount: -2 }, { stat: 'happiness', amount: 2 }],
        flagChanges: [{ key: 'hadPartTimeJob', value: true }],
        outcome: 'You hand your first paycheck to your mother. She hugs you without saying anything.',
        seedsThreads: [{
          key: 'self_made_thread',
          category: 'career',
          payload: { origin: 'family_hardship' },
          triggerMinAge: 25,
          triggerMaxAge: 45,
        }],
      },
      {
        id: 'focus_on_escape',
        label: 'Channel it into studying harder',
        statDeltas: [{ stat: 'intelligence', amount: 6 }, { stat: 'discipline', amount: 4 }, { stat: 'happiness', amount: -3 }],
        flagChanges: [],
        outcome: 'Poverty is one of the most reliable motivators. You channel every bit of it.',
      },
    ],
  },
  {
    id: 'ad_volunteer',
    title: 'The Opportunity',
    description: 'A local community centre is looking for volunteer help. No pay. Just time.',
    stages: [LifeStage.Adolescence],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'volunteer',
        label: 'Sign up',
        statDeltas: [{ stat: 'charisma', amount: 4 }, { stat: 'happiness', amount: 5 }, { stat: 'discipline', amount: 3 }],
        flagChanges: [],
        outcome: 'You discover the strange satisfaction of work that isn\'t transactional.',
      },
      {
        id: 'skip',
        label: 'You already have enough commitments',
        statDeltas: [{ stat: 'intelligence', amount: 2 }],
        flagChanges: [],
        outcome: 'Fair. You channel the time into something else.',
      },
    ],
  },
  {
    id: 'ad_parent_illness',
    title: 'The Diagnosis',
    description: 'One of your parents is diagnosed with a serious but treatable illness. The hospital becomes a second home.',
    stages: [LifeStage.Adolescence],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'be_the_rock',
        label: 'Step up and hold the family together',
        statDeltas: [{ stat: 'discipline', amount: 6 }, { stat: 'happiness', amount: -6 }, { stat: 'charisma', amount: 4 }],
        flagChanges: [],
        outcome: 'You grow up faster than you should have. The person who comes out the other side is formidable.',
        seedsThreads: [{
          key: 'caregiver_thread',
          category: 'personal',
          payload: { origin: 'parent_illness' },
          triggerMinAge: 30,
          triggerMaxAge: 60,
        }],
      },
      {
        id: 'fall_apart',
        label: 'Lean on friends and a counsellor',
        statDeltas: [{ stat: 'charisma', amount: 3 }, { stat: 'happiness', amount: -4 }, { stat: 'intelligence', amount: 3 }],
        flagChanges: [],
        outcome: 'Asking for help is its own kind of strength. Your friends show you who they are.',
      },
    ],
  },
  {
    id: 'ad_entrepreneurial_spark',
    title: 'The Side Hustle',
    description: 'You notice a gap in your school: nobody is selling handmade phone cases or custom prints. You could.',
    stages: [LifeStage.Adolescence],
    statConditions: [{ stat: 'creativity', operator: 'gte', value: 50 }],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'start_it',
        label: 'Start the business',
        statDeltas: [{ stat: 'discipline', amount: 4 }, { stat: 'creativity', amount: 4 }, { stat: 'charisma', amount: 3 }],
        flagChanges: [{ key: 'hasEntrepreneurialExperience', value: true }],
        outcome: 'You sell out your first batch by lunchtime. The experience changes how you see the world.',
        seedsThreads: [{
          key: 'entrepreneur_thread',
          category: 'career',
          payload: { origin: 'teen_business' },
          triggerMinAge: 22,
          triggerMaxAge: 35,
        }],
      },
      {
        id: 'too_risky',
        label: 'Stick to studying',
        statDeltas: [{ stat: 'intelligence', amount: 3 }],
        flagChanges: [],
        outcome: 'Someone else starts it next month. They retire early.',
      },
    ],
  },
  {
    id: 'ad_health_scare',
    title: 'The Test Results',
    description: 'A routine check-up flags something unexpected. More tests are needed.',
    stages: [LifeStage.Adolescence],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 10,
    choices: [
      {
        id: 'face_it',
        label: 'Follow up immediately and tell your parents',
        statDeltas: [{ stat: 'health', amount: 3 }, { stat: 'happiness', amount: -3 }, { stat: 'discipline', amount: 3 }],
        flagChanges: [],
        outcome: 'It turns out to be minor — but catching it early mattered. You learn to take your health seriously.',
      },
      {
        id: 'ignore',
        label: 'Ignore it — it\'s probably nothing',
        statDeltas: [{ stat: 'health', amount: -4 }, { stat: 'happiness', amount: 2 }],
        flagChanges: [],
        outcome: 'It probably was nothing. This time. The habit of ignoring signals persists.',
      },
    ],
  },
  {
    id: 'ad_academic_competition',
    title: 'The Championship',
    description: 'Your school qualifies for a regional academic competition. Your teacher nominates you to compete.',
    stages: [LifeStage.Adolescence],
    statConditions: [{ stat: 'intelligence', operator: 'gte', value: 60 }],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'compete',
        label: 'Represent your school',
        statDeltas: [{ stat: 'intelligence', amount: 5 }, { stat: 'discipline', amount: 4 }, { stat: 'charisma', amount: 3 }, { stat: 'stress', amount: 12 }],
        flagChanges: [],
        outcome: 'You place third. The preparation alone was worth it.',
      },
      {
        id: 'decline',
        label: 'Pass — the pressure isn\'t worth it',
        statDeltas: [{ stat: 'happiness', amount: 3 }],
        flagChanges: [],
        outcome: 'Healthy self-knowledge is underrated.',
      },
    ],
  },
  {
    id: 'ad_identity',
    title: 'Who Are You?',
    description: 'A late night. A mirror. The question arrives without warning: who do you actually want to be?',
    stages: [LifeStage.Adolescence],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'write_it_down',
        label: 'Write down what you actually believe',
        statDeltas: [{ stat: 'intelligence', amount: 4 }, { stat: 'creativity', amount: 4 }, { stat: 'happiness', amount: 4 }],
        flagChanges: [],
        outcome: 'The act of writing makes it real. You fold the page up and keep it.',
      },
      {
        id: 'let_it_be',
        label: 'Let the question sit unanswered',
        statDeltas: [{ stat: 'happiness', amount: 2 }],
        flagChanges: [],
        outcome: 'Some questions mature better when left alone. Wisdom or avoidance? Both, maybe.',
      },
    ],
  },
  {
    id: 'ad_online_fame',
    title: 'Going Viral',
    description: 'You post something online — art, a rant, a video — and it blows up overnight. Strangers are arguing about you.',
    stages: [LifeStage.Adolescence],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'lean_in',
        label: 'Lean into it and keep posting',
        statDeltas: [{ stat: 'charisma', amount: 5 }, { stat: 'creativity', amount: 4 }, { stat: 'stress', amount: 15 }],
        flagChanges: [],
        outcome: 'You grow a following. You also grow a skin thicker than any classroom could give you.',
      },
      {
        id: 'log_off',
        label: 'Delete the account and walk away',
        statDeltas: [{ stat: 'happiness', amount: 4 }, { stat: 'discipline', amount: 3 }],
        flagChanges: [],
        outcome: 'The internet forgets in 48 hours. You don\'t. But you choose what that means for you.',
      },
    ],
  },
  {
    id: 'ad_graduation',
    title: 'The Last Day',
    description: 'High school ends today. The whole school smells like sunscreen and relief.',
    stages: [LifeStage.Adolescence],
    statConditions: [],
    flagConditions: [{ key: 'hasHighSchool', value: false }],
    weight: 3,
    cooldownYears: 99,
    choices: [
      {
        id: 'celebrate_big',
        label: 'Go out and celebrate until sunrise',
        statDeltas: [{ stat: 'happiness', amount: 8 }, { stat: 'charisma', amount: 3 }, { stat: 'health', amount: -2 }],
        flagChanges: [{ key: 'hasHighSchool', value: true }],
        outcome: 'You will remember this night when you are very old and very happy.',
      },
      {
        id: 'quiet_reflection',
        label: 'Spend the evening thinking about what\'s next',
        statDeltas: [{ stat: 'intelligence', amount: 3 }, { stat: 'happiness', amount: 5 }],
        flagChanges: [{ key: 'hasHighSchool', value: true }],
        outcome: 'You sit with the weight of it. Tomorrow the world starts in earnest.',
      },
    ],
  },
  {
    id: 'ad_creative_passion',
    title: 'The Project',
    description: 'You have been working on something — a story, a song, a painting — in secret for months. It\'s almost done.',
    stages: [LifeStage.Adolescence],
    statConditions: [{ stat: 'creativity', operator: 'gte', value: 55 }],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'share',
        label: 'Share it with the world',
        statDeltas: [{ stat: 'creativity', amount: 6 }, { stat: 'charisma', amount: 4 }, { stat: 'happiness', amount: 5 }],
        flagChanges: [],
        outcome: 'It finds its audience. Not huge — but real. Real is enough.',
      },
      {
        id: 'keep_it',
        label: 'Keep it. It\'s not ready.',
        statDeltas: [{ stat: 'creativity', amount: 4 }, { stat: 'intelligence', amount: 2 }],
        flagChanges: [],
        outcome: 'You\'ll know when it\'s ready. Probably.',
      },
    ],
  },
  {
    id: 'ad_rebellion',
    title: 'The Rules',
    description: 'You have been pushing against your parents\' rules for months. Tonight feels like a breaking point.',
    stages: [LifeStage.Adolescence],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'break_free',
        label: 'Sneak out',
        statDeltas: [{ stat: 'charisma', amount: 3 }, { stat: 'happiness', amount: 4 }, { stat: 'discipline', amount: -3 }],
        flagChanges: [],
        outcome: 'You don\'t get caught. This time. But the pattern is set.',
      },
      {
        id: 'talk_it_out',
        label: 'Have an honest conversation instead',
        statDeltas: [{ stat: 'charisma', amount: 5 }, { stat: 'intelligence', amount: 3 }, { stat: 'happiness', amount: 2 }],
        flagChanges: [],
        outcome: 'They listen, surprisingly. Some rules loosen. You earned that.',
      },
    ],
  },
];
