import { LifeStage } from '@lifeverse/shared';
import type { GameEvent } from '@lifeverse/shared';

export const adultEvents: GameEvent[] = [
  {
    id: 'a_promotion_opportunity',
    title: 'The Conversation',
    description: 'Your manager pulls you aside: "There\'s a senior role opening. I think you\'re ready. But it\'ll be demanding."',
    stages: [LifeStage.Adult],
    statConditions: [{ stat: 'discipline', operator: 'gte', value: 55 }],
    flagConditions: [{ key: 'isEmployed', value: true }],
    weight: 2,
    cooldownYears: 4,
    choices: [
      {
        id: 'go_for_it',
        label: 'Put your name forward',
        statDeltas: [{ stat: 'discipline', amount: 5 }, { stat: 'charisma', amount: 3 }, { stat: 'stress', amount: 12 }],
        flagChanges: [],
        outcome: 'You get it. The first week in the new role is equal parts terrifying and electric.',
      },
      {
        id: 'not_yet',
        label: 'Ask for more time to prepare',
        statDeltas: [{ stat: 'intelligence', amount: 4 }, { stat: 'discipline', amount: 4 }],
        flagChanges: [],
        outcome: 'You spend three months preparing so thoroughly that the next conversation is inevitable.',
      },
    ],
  },
  {
    id: 'a_child_struggles',
    title: 'The Report Card',
    description: 'Your child\'s teacher calls. They\'re falling behind. Something is wrong and school isn\'t catching it.',
    stages: [LifeStage.Adult],
    statConditions: [],
    flagConditions: [{ key: 'hasChildren', value: true }],
    weight: 2,
    cooldownYears: 5,
    choices: [
      {
        id: 'tutor_yourself',
        label: 'Spend evenings tutoring them yourself',
        statDeltas: [{ stat: 'intelligence', amount: 3 }, { stat: 'discipline', amount: 4 }, { stat: 'happiness', amount: 4 }, { stat: 'stress', amount: 8 }],
        flagChanges: [],
        outcome: 'Slow going. But your evenings together create something neither school nor tutor could.',
      },
      {
        id: 'hire_tutor',
        label: 'Hire a specialist tutor',
        statDeltas: [{ stat: 'happiness', amount: 3 }],
        flagChanges: [],
        outcome: 'The right person changes everything. Six months later the school rings with good news.',
      },
      {
        id: 'investigate',
        label: 'Push for a proper educational assessment',
        statDeltas: [{ stat: 'intelligence', amount: 4 }, { stat: 'charisma', amount: 3 }, { stat: 'happiness', amount: 3 }],
        flagChanges: [],
        outcome: 'They are diagnosed with dyslexia. Now the school must provide proper support. You fought for this.',
      },
    ],
  },
  {
    id: 'a_health_scare',
    title: 'The Results',
    description: 'Your doctor calls about something in your routine blood work. "It\'s not urgent but we should talk."',
    stages: [LifeStage.Adult],
    statConditions: [],
    flagConditions: [],
    weight: 2,
    cooldownYears: 8,
    choices: [
      {
        id: 'act_immediately',
        label: 'See a specialist immediately',
        statDeltas: [{ stat: 'health', amount: 5 }, { stat: 'happiness', amount: -3 }, { stat: 'stress', amount: 10 }],
        flagChanges: [],
        outcome: 'Caught early, managed effectively. The anxiety cost more than the condition did.',
      },
      {
        id: 'lifestyle_change',
        label: 'Overhaul your lifestyle before escalating',
        statDeltas: [{ stat: 'health', amount: 4 }, { stat: 'discipline', amount: 6 }, { stat: 'happiness', amount: 3 }],
        flagChanges: [],
        outcome: 'Six months of real effort. The follow-up shows dramatic improvement.',
      },
      {
        id: 'ignore',
        label: 'Decide you feel fine and ignore it',
        statDeltas: [{ stat: 'health', amount: -6 }, { stat: 'happiness', amount: 2 }],
        flagChanges: [],
        outcome: 'Two years later it becomes urgent. What was manageable is now expensive.',
      },
    ],
  },
  {
    id: 'a_marriage_proposal',
    title: 'The Question',
    description: 'You and your partner have been together for years. The question hasn\'t been asked yet. Tonight feels different.',
    stages: [LifeStage.Adult],
    statConditions: [],
    flagConditions: [{ key: 'hasPartner', value: true }, { key: 'isMarried', value: false }],
    weight: 2,
    cooldownYears: 99,
    choices: [
      {
        id: 'propose',
        label: 'Ask the question',
        statDeltas: [{ stat: 'happiness', amount: 10 }, { stat: 'charisma', amount: 3 }],
        flagChanges: [{ key: 'isMarried', value: true }],
        outcome: 'Yes. The word lands and the whole room seems to rearrange itself.',
      },
      {
        id: 'wait',
        label: 'Wait — you\'re not quite ready',
        statDeltas: [{ stat: 'intelligence', amount: 2 }],
        flagChanges: [],
        outcome: 'The moment passes. Another will come when you\'re sure.',
      },
    ],
  },
  {
    id: 'a_colleague_betrayal',
    title: 'Stabbed In The Back',
    description: 'You find out a colleague has been quietly taking credit for your ideas with your boss. For months.',
    stages: [LifeStage.Adult],
    statConditions: [],
    flagConditions: [{ key: 'isEmployed', value: true }],
    weight: 1,
    cooldownYears: 6,
    choices: [
      {
        id: 'confront_publicly',
        label: 'Raise it in the next team meeting',
        statDeltas: [{ stat: 'charisma', amount: 4 }, { stat: 'discipline', amount: 3 }, { stat: 'stress', amount: 12 }],
        flagChanges: [],
        outcome: 'Uncomfortable. But the pattern stops. Your boss makes a quiet note.',
      },
      {
        id: 'go_to_management',
        label: 'Document it and speak to HR',
        statDeltas: [{ stat: 'intelligence', amount: 4 }, { stat: 'discipline', amount: 4 }],
        flagChanges: [],
        outcome: 'Formal process. Paper trail. Slower but cleaner.',
        seedsThreads: [{
          key: 'workplace_justice_thread',
          category: 'career',
          payload: { betray: true },
          triggerMinAge: 40,
          triggerMaxAge: 60,
        }],
      },
      {
        id: 'use_it',
        label: 'Use it as motivation to become irreplaceable',
        statDeltas: [{ stat: 'discipline', amount: 6 }, { stat: 'intelligence', amount: 4 }, { stat: 'happiness', amount: -3 }],
        flagChanges: [],
        outcome: 'Anger is excellent fuel if you point it in the right direction.',
      },
    ],
  },
  {
    id: 'a_house_opportunity',
    title: 'The Property',
    description: 'A friend in real estate tips you off about a house below market value. The mortgage is steep. The timing is uncertain.',
    stages: [LifeStage.Adult],
    statConditions: [],
    flagConditions: [{ key: 'hasHouse', value: false }, { key: 'isEmployed', value: true }],
    weight: 2,
    cooldownYears: 99,
    choices: [
      {
        id: 'buy',
        label: 'Buy it',
        statDeltas: [{ stat: 'happiness', amount: 7 }, { stat: 'discipline', amount: 4 }, { stat: 'stress', amount: 10 }],
        flagChanges: [{ key: 'hasHouse', value: true }, { key: 'hasHouseMortgage', value: true }],
        outcome: 'The keys sit heavy in your hand. This is permanent. This is yours.',
      },
      {
        id: 'keep_renting',
        label: 'Keep renting and save longer',
        statDeltas: [{ stat: 'discipline', amount: 4 }],
        flagChanges: [],
        outcome: 'The right house will come. You watch your savings grow.',
      },
    ],
  },
  {
    id: 'a_side_business',
    title: 'The Second Income',
    description: 'A skill you\'ve been developing could generate real side income. But starting a business takes time you barely have.',
    stages: [LifeStage.Adult],
    statConditions: [{ stat: 'discipline', operator: 'gte', value: 55 }],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'start_it',
        label: 'Start the side business',
        statDeltas: [{ stat: 'discipline', amount: 5 }, { stat: 'creativity', amount: 4 }, { stat: 'stress', amount: 15 }, { stat: 'happiness', amount: 4 }],
        flagChanges: [{ key: 'hasSideProject', value: true }],
        outcome: 'Twelve-hour days for three months. Then the first client. Then the second.',
      },
      {
        id: 'protect_time',
        label: 'Protect your downtime — you\'re already stretched',
        statDeltas: [{ stat: 'happiness', amount: 4 }, { stat: 'health', amount: 3 }],
        flagChanges: [],
        outcome: 'Some of the best decisions are the ones you don\'t make.',
      },
    ],
  },
  {
    id: 'a_work_life_crisis',
    title: 'The Burnout',
    description: 'You haven\'t taken a real day off in three years. Your family has noticed. Your body has noticed.',
    stages: [LifeStage.Adult],
    statConditions: [{ stat: 'stress', operator: 'gte', value: 70 }],
    flagConditions: [],
    weight: 2,
    cooldownYears: 5,
    choices: [
      {
        id: 'take_break',
        label: 'Take a proper two-week break',
        statDeltas: [{ stat: 'happiness', amount: 8 }, { stat: 'health', amount: 6 }, { stat: 'stress', amount: -30 }],
        flagChanges: [],
        outcome: 'The world did not end. It is better. So are you.',
      },
      {
        id: 'push_through',
        label: 'Push through it — there\'s no good time',
        statDeltas: [{ stat: 'health', amount: -6 }, { stat: 'happiness', amount: -6 }, { stat: 'stress', amount: 10 }],
        flagChanges: [],
        outcome: 'The wall arrives on its own schedule. It\'s harder when you\'re unprepared.',
      },
      {
        id: 'restructure',
        label: 'Have an honest conversation with your family about priorities',
        statDeltas: [{ stat: 'happiness', amount: 7 }, { stat: 'charisma', amount: 4 }, { stat: 'stress', amount: -15 }],
        flagChanges: [],
        outcome: 'The conversation is harder than you expected. What comes after is better than you hoped.',
      },
    ],
  },
  {
    id: 'a_career_change',
    title: 'The Other Path',
    description: 'A former colleague calls. They\'ve started something new and want you involved. It means starting over in a new field.',
    stages: [LifeStage.Adult],
    statConditions: [],
    flagConditions: [{ key: 'isEmployed', value: true }],
    weight: 1,
    cooldownYears: 10,
    choices: [
      {
        id: 'take_the_leap',
        label: 'Take the leap',
        statDeltas: [{ stat: 'charisma', amount: 4 }, { stat: 'creativity', amount: 5 }, { stat: 'discipline', amount: 4 }, { stat: 'stress', amount: 15 }],
        flagChanges: [],
        outcome: 'You trade seniority for possibility. It\'s a reset and a beginning.',
      },
      {
        id: 'stay',
        label: 'Stay where you are and keep building',
        statDeltas: [{ stat: 'discipline', amount: 4 }, { stat: 'intelligence', amount: 3 }],
        flagChanges: [],
        outcome: 'Depth over breadth. You become exceptional at what you do.',
      },
    ],
  },
  {
    id: 'a_community_leadership',
    title: 'The Committee',
    description: 'Your neighbourhood association asks if you\'d like to chair a community improvement project.',
    stages: [LifeStage.Adult],
    statConditions: [{ stat: 'charisma', operator: 'gte', value: 55 }],
    flagConditions: [],
    weight: 1,
    cooldownYears: 10,
    choices: [
      {
        id: 'accept',
        label: 'Accept the role',
        statDeltas: [{ stat: 'charisma', amount: 5 }, { stat: 'happiness', amount: 5 }, { stat: 'discipline', amount: 3 }],
        flagChanges: [],
        outcome: 'The project works. A park is renovated. Twenty people know your name now.',
      },
      {
        id: 'decline',
        label: 'Politely decline',
        statDeltas: [{ stat: 'happiness', amount: 2 }],
        flagChanges: [],
        outcome: 'There\'s only so much time. Choosing is itself a discipline.',
      },
    ],
  },
  {
    id: 'a_unexpected_inheritance',
    title: 'The Letter',
    description: 'A letter from a solicitor. A distant relative you barely knew has left you something in their will.',
    stages: [LifeStage.Adult],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'invest',
        label: 'Invest it quietly',
        statDeltas: [{ stat: 'intelligence', amount: 4 }, { stat: 'discipline', amount: 3 }],
        flagChanges: [],
        outcome: 'A decade later the investment has grown into something life-changing.',
      },
      {
        id: 'spend_meaningfully',
        label: 'Use it to change your family\'s life now',
        statDeltas: [{ stat: 'happiness', amount: 8 }, { stat: 'charisma', amount: 3 }],
        flagChanges: [],
        outcome: 'A family trip. Paying off a debt. Sending your child to a better school. Real change, now.',
      },
    ],
  },
  {
    id: 'a_family_reunion',
    title: 'The Reunion',
    description: 'A family reunion surfaces people you haven\'t seen in a decade. Old tensions come with them.',
    stages: [LifeStage.Adult],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 8,
    choices: [
      {
        id: 'old_wounds',
        label: 'Bring up old tensions — it\'s time',
        statDeltas: [{ stat: 'charisma', amount: 4 }, { stat: 'happiness', amount: 3 }, { stat: 'stress', amount: 10 }],
        flagChanges: [],
        outcome: 'Some conversations need to happen at a family reunion. Some don\'t. You\'re not sure which this was.',
      },
      {
        id: 'keep_peace',
        label: 'Be the peacekeeper',
        statDeltas: [{ stat: 'charisma', amount: 4 }, { stat: 'discipline', amount: 3 }, { stat: 'happiness', amount: 4 }],
        flagChanges: [],
        outcome: 'Everyone leaves smiling. The peace is real even if the problems aren\'t solved.',
      },
    ],
  },
  {
    id: 'a_midlife_question',
    title: 'The Mirror',
    description: 'Late night. Numbers on a screen. A question you\'ve been avoiding: is this the life you chose, or the one that happened to you?',
    stages: [LifeStage.Adult],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 10,
    choices: [
      {
        id: 'change_something',
        label: 'Decide to change one meaningful thing',
        statDeltas: [{ stat: 'happiness', amount: 6 }, { stat: 'creativity', amount: 5 }, { stat: 'discipline', amount: 4 }],
        flagChanges: [],
        outcome: 'One real change. Not a new gym membership — something true. The question stops visiting.',
      },
      {
        id: 'accept',
        label: 'Accept it with peace',
        statDeltas: [{ stat: 'happiness', amount: 5 }, { stat: 'intelligence', amount: 3 }],
        flagChanges: [],
        outcome: 'Not resignation — active acceptance. The difference matters enormously.',
      },
      {
        id: 'spiral',
        label: 'Let the question spiral',
        statDeltas: [{ stat: 'happiness', amount: -5 }, { stat: 'intelligence', amount: 4 }, { stat: 'creativity', amount: 4 }],
        flagChanges: [],
        outcome: 'Painful. But the spiral digs up something true. Sometimes the descent is the work.',
      },
    ],
  },
  {
    id: 'a_financial_setback',
    title: 'The Crash',
    description: 'A financial decision goes badly wrong. The savings take a significant hit.',
    stages: [LifeStage.Adult],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 8,
    choices: [
      {
        id: 'rebuild_immediately',
        label: 'Cut everything non-essential and rebuild',
        statDeltas: [{ stat: 'discipline', amount: 7 }, { stat: 'happiness', amount: -4 }, { stat: 'stress', amount: 8 }],
        flagChanges: [],
        outcome: 'Painful austerity. But within three years you\'re back where you were — and smarter.',
      },
      {
        id: 'seek_advice',
        label: 'Get professional financial advice',
        statDeltas: [{ stat: 'intelligence', amount: 5 }, { stat: 'discipline', amount: 4 }],
        flagChanges: [],
        outcome: 'A professional catches three things you missed. The recovery is faster and more structured.',
      },
    ],
  },
  {
    id: 'a_parenting_moment',
    title: 'The Talk',
    description: 'Your teenager asks you something honest and uncomfortable. They\'re looking at you like they\'re weighing whether you can be trusted with the real version of themselves.',
    stages: [LifeStage.Adult],
    statConditions: [],
    flagConditions: [{ key: 'hasChildren', value: true }],
    weight: 2,
    cooldownYears: 5,
    choices: [
      {
        id: 'be_fully_honest',
        label: 'Answer with complete honesty',
        statDeltas: [{ stat: 'charisma', amount: 5 }, { stat: 'happiness', amount: 6 }, { stat: 'intelligence', amount: 3 }],
        flagChanges: [],
        outcome: 'The conversation lasts three hours. They trust you more after this than they ever have.',
      },
      {
        id: 'protective_deflect',
        label: 'Give them a safe, partial answer',
        statDeltas: [{ stat: 'charisma', amount: 2 }, { stat: 'happiness', amount: 2 }],
        flagChanges: [],
        outcome: 'They accept it. They also learned something about your limits.',
      },
    ],
  },
];
