import { LifeStage } from '@lifeverse/shared';
import type { GameEvent } from '@lifeverse/shared';

export const childhoodEvents: GameEvent[] = [
  {
    id: 'ch_new_neighbor',
    title: 'The New Kid',
    description: 'A family moves in next door and their kid — Marcus — knocks on your door with a football in hand.',
    stages: [LifeStage.Childhood],
    statConditions: [],
    flagConditions: [],
    weight: 2,
    cooldownYears: 99,
    choices: [
      {
        id: 'befriend',
        label: 'Invite Marcus in',
        statDeltas: [{ stat: 'charisma', amount: 3 }, { stat: 'happiness', amount: 4 }],
        flagChanges: [{ key: 'hasFriendMarcus', value: true }],
        outcome: 'You spend the afternoon playing until dark. You have made your first real friend.',
        seedsThreads: [{
          key: 'marcus_thread',
          category: 'personal',
          payload: { name: 'Marcus', initialBond: 'high' },
          triggerMinAge: 14,
          triggerMaxAge: 35,
        }],
      },
      {
        id: 'ignore',
        label: 'Pretend you are busy',
        statDeltas: [{ stat: 'charisma', amount: -2 }],
        flagChanges: [],
        outcome: 'You watch from behind the curtain. Marcus goes home alone.',
      },
    ],
  },
  {
    id: 'ch_parents_argue',
    title: 'Raised Voices',
    description: 'Late at night you hear your parents argue through the wall. Their words are sharp and unfamiliar.',
    stages: [LifeStage.Childhood],
    statConditions: [],
    flagConditions: [],
    weight: 2,
    cooldownYears: 3,
    choices: [
      {
        id: 'talk',
        label: 'Go talk to them',
        statDeltas: [{ stat: 'charisma', amount: 3 }, { stat: 'happiness', amount: -3 }],
        flagChanges: [],
        outcome: 'They stop arguing when they see your face. The night stays tense but quiet after that.',
      },
      {
        id: 'stay_room',
        label: 'Pull the covers over your head',
        statDeltas: [{ stat: 'happiness', amount: -5 }, { stat: 'intelligence', amount: 2 }],
        flagChanges: [],
        outcome: 'You read by torchlight until you fall asleep. Some things are beyond your control.',
        seedsThreads: [{
          key: 'family_tension_thread',
          category: 'trauma',
          payload: { origin: 'childhood_fight' },
          triggerMinAge: 20,
          triggerMaxAge: 45,
        }],
      },
    ],
  },
  {
    id: 'ch_discover_reading',
    title: 'The Library',
    description: 'Your teacher takes the class to the school library. One book — a story about a scientist who changed the world — grabs you and won\'t let go.',
    stages: [LifeStage.Childhood],
    statConditions: [],
    flagConditions: [],
    weight: 2,
    cooldownYears: 99,
    choices: [
      {
        id: 'read_every_night',
        label: 'Read every night before bed',
        statDeltas: [{ stat: 'intelligence', amount: 5 }, { stat: 'creativity', amount: 3 }],
        flagChanges: [{ key: 'isAReader', value: true }],
        outcome: 'Words become your window to worlds you haven\'t lived yet.',
      },
      {
        id: 'prefer_outside',
        label: 'Return it unfinished — the outdoors calls',
        statDeltas: [{ stat: 'health', amount: 4 }, { stat: 'happiness', amount: 3 }],
        flagChanges: [],
        outcome: 'You\'d rather build a den in the woods than read about one.',
      },
    ],
  },
  {
    id: 'ch_school_bully',
    title: 'The Bully',
    description: 'Jake has been taking your lunch and calling you names. Today he corners you in the corridor in front of everyone.',
    stages: [LifeStage.Childhood],
    statConditions: [],
    flagConditions: [],
    weight: 2,
    cooldownYears: 5,
    choices: [
      {
        id: 'stand_up',
        label: 'Stand your ground',
        statDeltas: [{ stat: 'charisma', amount: 4 }, { stat: 'discipline', amount: 3 }, { stat: 'health', amount: -3 }],
        flagChanges: [],
        outcome: 'Your nose bleeds but you don\'t back down. Jake doesn\'t bother you again.',
      },
      {
        id: 'walk_away',
        label: 'Walk away and tell a teacher',
        statDeltas: [{ stat: 'discipline', amount: 4 }, { stat: 'happiness', amount: -3 }],
        flagChanges: [],
        outcome: 'Smart. But it still stings. You spend lunch alone that week.',
      },
      {
        id: 'befriend_bully',
        label: 'Try to understand him',
        statDeltas: [{ stat: 'charisma', amount: 5 }, { stat: 'happiness', amount: 2 }],
        flagChanges: [],
        outcome: 'You learn Jake\'s parents are going through a divorce. He becomes oddly protective of you.',
      },
    ],
  },
  {
    id: 'ch_first_pet',
    title: 'A Dog Named Biscuit',
    description: 'Your parents surprise you with a golden retriever puppy on your birthday. He is already chewing your shoe.',
    stages: [LifeStage.Childhood],
    statConditions: [],
    flagConditions: [{ key: 'hasPet', value: false }],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'embrace',
        label: 'Take full responsibility for him',
        statDeltas: [{ stat: 'discipline', amount: 4 }, { stat: 'happiness', amount: 5 }],
        flagChanges: [{ key: 'hasPet', value: true }],
        outcome: 'Morning walks and feeding schedules teach you what responsibility actually feels like.',
      },
      {
        id: 'leave_to_parents',
        label: 'Let your parents handle the work',
        statDeltas: [{ stat: 'happiness', amount: 4 }],
        flagChanges: [{ key: 'hasPet', value: true }],
        outcome: 'You love Biscuit but the lessons don\'t quite stick.',
      },
    ],
  },
  {
    id: 'ch_teacher_notices',
    title: 'The Teacher\'s Note',
    description: 'Your teacher writes a note home: "Your child shows exceptional potential. Please consider extra tutoring."',
    stages: [LifeStage.Childhood],
    statConditions: [{ stat: 'intelligence', operator: 'gte', value: 55 }],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'accept_tutoring',
        label: 'Accept the extra lessons',
        statDeltas: [{ stat: 'intelligence', amount: 6 }, { stat: 'discipline', amount: 3 }, { stat: 'happiness', amount: -2 }],
        flagChanges: [{ key: 'wasIdentifiedGifted', value: true }],
        outcome: 'Weekend lessons are boring but your mind sharpens like a blade.',
        seedsThreads: [{
          key: 'scholar_path',
          category: 'career',
          payload: { origin: 'childhood_tutoring' },
          triggerMinAge: 17,
          triggerMaxAge: 22,
        }],
      },
      {
        id: 'decline',
        label: 'Decline — weekends are sacred',
        statDeltas: [{ stat: 'happiness', amount: 4 }, { stat: 'health', amount: 3 }],
        flagChanges: [],
        outcome: 'You spend those hours climbing trees and building ramps. No regrets.',
      },
    ],
  },
  {
    id: 'ch_discover_music',
    title: 'The Old Guitar',
    description: 'Your uncle leaves behind a battered acoustic guitar when he visits. Late at night you pluck out something that almost sounds like a song.',
    stages: [LifeStage.Childhood],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'practice',
        label: 'Practice every day',
        statDeltas: [{ stat: 'creativity', amount: 5 }, { stat: 'discipline', amount: 3 }, { stat: 'happiness', amount: 3 }],
        flagChanges: [{ key: 'playsMusic', value: true }],
        outcome: 'Your fingertips harden. So does your dedication.',
        seedsThreads: [{
          key: 'music_path',
          category: 'personal',
          payload: { instrument: 'guitar' },
          triggerMinAge: 15,
          triggerMaxAge: 30,
        }],
      },
      {
        id: 'lose_interest',
        label: 'Lose interest after a week',
        statDeltas: [{ stat: 'happiness', amount: 1 }],
        flagChanges: [],
        outcome: 'The guitar collects dust under your bed. Maybe next time.',
      },
    ],
  },
  {
    id: 'ch_summer_camp',
    title: 'Summer Camp',
    description: 'Your parents sign you up for a week of summer camp in the mountains. You know no one.',
    stages: [LifeStage.Childhood],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'dive_in',
        label: 'Throw yourself into every activity',
        statDeltas: [{ stat: 'charisma', amount: 4 }, { stat: 'health', amount: 4 }, { stat: 'happiness', amount: 5 }],
        flagChanges: [],
        outcome: 'By day three you\'re leading the campfire sing-along. You\'ve found your voice.',
      },
      {
        id: 'stay_quiet',
        label: 'Keep to yourself and observe',
        statDeltas: [{ stat: 'intelligence', amount: 3 }, { stat: 'creativity', amount: 3 }],
        flagChanges: [],
        outcome: 'You fill a whole notebook with observations. You leave knowing more about people than most adults do.',
      },
    ],
  },
  {
    id: 'ch_family_moves',
    title: 'The Moving Boxes',
    description: 'Your parents announce the family is moving to a new city. You have one week left at your school.',
    stages: [LifeStage.Childhood],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'embrace_change',
        label: 'See it as an adventure',
        statDeltas: [{ stat: 'charisma', amount: 3 }, { stat: 'happiness', amount: 2 }, { stat: 'discipline', amount: 3 }],
        flagChanges: [],
        outcome: 'The new city smells different. By month two, you prefer it.',
      },
      {
        id: 'devastated',
        label: 'Grieve what you\'re losing',
        statDeltas: [{ stat: 'happiness', amount: -4 }, { stat: 'intelligence', amount: 3 }],
        flagChanges: [],
        outcome: 'The loss teaches you something real: not everything lasts. You carry that knowledge carefully.',
      },
    ],
  },
  {
    id: 'ch_sports_tryout',
    title: 'The Tryouts',
    description: 'The school sports team is holding tryouts. Your friends dare you to sign up.',
    stages: [LifeStage.Childhood],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'try_out',
        label: 'Give it everything',
        statDeltas: [{ stat: 'health', amount: 5 }, { stat: 'discipline', amount: 4 }, { stat: 'charisma', amount: 2 }],
        flagChanges: [{ key: 'playsTeamSport', value: true }],
        outcome: 'You make the team. Pre-dawn practices will define the next few years.',
      },
      {
        id: 'skip',
        label: 'Skip the tryouts',
        statDeltas: [{ stat: 'creativity', amount: 3 }],
        flagChanges: [],
        outcome: 'You spend tryout afternoon working on an art project. Different path, same potential.',
      },
    ],
  },
  {
    id: 'ch_grandparent_lesson',
    title: 'Grandma\'s Advice',
    description: 'Your grandmother sits you down while the rest of the family watches TV. She says: "I want to tell you something before I can\'t."',
    stages: [LifeStage.Childhood],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'listen_deeply',
        label: 'Listen and ask questions',
        statDeltas: [{ stat: 'intelligence', amount: 4 }, { stat: 'happiness', amount: 5 }, { stat: 'charisma', amount: 2 }],
        flagChanges: [],
        outcome: 'She tells you about regret and love and the one thing she would do differently. You remember it forever.',
      },
      {
        id: 'polite_but_distracted',
        label: 'Nod along while thinking about something else',
        statDeltas: [{ stat: 'happiness', amount: 2 }],
        flagChanges: [],
        outcome: 'You smile and nod. You\'ll wish you\'d listened.',
      },
    ],
  },
  {
    id: 'ch_childhood_illness',
    title: 'A Long Winter',
    description: 'You spend three months seriously ill. The world carries on without you.',
    stages: [LifeStage.Childhood],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 10,
    choices: [
      {
        id: 'read_and_learn',
        label: 'Read everything you can reach from your bed',
        statDeltas: [{ stat: 'health', amount: -5 }, { stat: 'intelligence', amount: 6 }, { stat: 'creativity', amount: 4 }],
        flagChanges: [],
        outcome: 'You emerge from illness knowing more than your classmates. Your body is weaker; your mind is not.',
      },
      {
        id: 'rest_and_recover',
        label: 'Rest and let your body heal',
        statDeltas: [{ stat: 'health', amount: -2 }, { stat: 'happiness', amount: 2 }],
        flagChanges: [],
        outcome: 'A full recovery. You come back to school hungry for normal.',
      },
    ],
  },
  {
    id: 'ch_art_class',
    title: 'The Art Competition',
    description: 'Your school holds an art competition. You\'ve been secretly working on something all semester.',
    stages: [LifeStage.Childhood],
    statConditions: [{ stat: 'creativity', operator: 'gte', value: 50 }],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'submit',
        label: 'Submit your best work',
        statDeltas: [{ stat: 'creativity', amount: 5 }, { stat: 'charisma', amount: 3 }, { stat: 'happiness', amount: 4 }],
        flagChanges: [],
        outcome: 'You win second place. Your teacher hangs your work in the hallway for a year.',
      },
      {
        id: 'too_scared',
        label: 'Decide it isn\'t good enough',
        statDeltas: [{ stat: 'discipline', amount: 2 }, { stat: 'happiness', amount: -2 }],
        flagChanges: [],
        outcome: 'You watch someone else win with work that\'s clearly worse than yours. You won\'t make that mistake again.',
      },
    ],
  },
  {
    id: 'ch_allowance_choice',
    title: 'The Allowance',
    description: 'Your parents start giving you a small weekly allowance. It burns a hole in your pocket.',
    stages: [LifeStage.Childhood],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'save_it',
        label: 'Save every penny',
        statDeltas: [{ stat: 'discipline', amount: 5 }, { stat: 'happiness', amount: -1 }],
        flagChanges: [],
        outcome: 'By the end of the year you buy something meaningful. Your friends are impressed — and jealous.',
      },
      {
        id: 'spend_it',
        label: 'Spend it immediately on fun',
        statDeltas: [{ stat: 'happiness', amount: 4 }, { stat: 'charisma', amount: 2 }],
        flagChanges: [],
        outcome: 'Life is for living. You share your spending with friends and become briefly very popular.',
      },
    ],
  },
  {
    id: 'ch_imaginary_world',
    title: 'The World You Built',
    description: 'You have been secretly building an elaborate imaginary world in your notebooks — maps, characters, rules.',
    stages: [LifeStage.Childhood],
    statConditions: [{ stat: 'creativity', operator: 'gte', value: 45 }],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'share_with_friend',
        label: 'Share it with your best friend',
        statDeltas: [{ stat: 'creativity', amount: 4 }, { stat: 'charisma', amount: 3 }, { stat: 'happiness', amount: 5 }],
        flagChanges: [],
        outcome: 'They immediately want to play in it. Your world gains its first citizen.',
      },
      {
        id: 'keep_secret',
        label: 'Keep it private — it\'s too personal',
        statDeltas: [{ stat: 'creativity', amount: 6 }, { stat: 'intelligence', amount: 2 }],
        flagChanges: [],
        outcome: 'The world grows deeper without outside influence. Some things are better kept sacred for now.',
      },
    ],
  },
  {
    id: 'ch_best_friend_leaves',
    title: 'Goodbye',
    description: 'Your best friend is moving away. Their last day at school is tomorrow.',
    stages: [LifeStage.Childhood],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'throw_party',
        label: 'Organise a goodbye party',
        statDeltas: [{ stat: 'charisma', amount: 4 }, { stat: 'happiness', amount: -2 }],
        flagChanges: [],
        outcome: 'It is the best bad day you\'ve had. The whole class cries a little.',
      },
      {
        id: 'write_letter',
        label: 'Write them a long letter',
        statDeltas: [{ stat: 'intelligence', amount: 3 }, { stat: 'creativity', amount: 3 }, { stat: 'happiness', amount: -3 }],
        flagChanges: [],
        outcome: 'They write back for two years. Then life takes over.',
      },
    ],
  },
  {
    id: 'ch_parents_divorce',
    title: 'Two Homes',
    description: 'Your parents sit you down. They are separating. You will split time between two houses.',
    stages: [LifeStage.Childhood],
    statConditions: [],
    flagConditions: [{ key: 'parentsDivorced', value: false }],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'stay_strong',
        label: 'Stay strong for everyone',
        statDeltas: [{ stat: 'discipline', amount: 4 }, { stat: 'happiness', amount: -6 }, { stat: 'charisma', amount: 3 }],
        flagChanges: [{ key: 'parentsDivorced', value: true }],
        outcome: 'You become the quiet anchor in both households. It costs more than you admit.',
        seedsThreads: [{
          key: 'family_fracture_thread',
          category: 'generational',
          payload: { severity: 'divorce' },
          triggerMinAge: 25,
          triggerMaxAge: 50,
          isGenerational: false,
        }],
      },
      {
        id: 'fall_apart',
        label: 'Let yourself grieve',
        statDeltas: [{ stat: 'happiness', amount: -8 }, { stat: 'intelligence', amount: 3 }],
        flagChanges: [{ key: 'parentsDivorced', value: true }],
        outcome: 'The grief is real and you feel it all. A school counsellor helps you put it into words.',
      },
    ],
  },
  {
    id: 'ch_science_project',
    title: 'The Science Fair',
    description: 'The school science fair is in two weeks. You have an idea nobody else has thought of.',
    stages: [LifeStage.Childhood],
    statConditions: [{ stat: 'intelligence', operator: 'gte', value: 50 }],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'go_all_in',
        label: 'Work nights to build the best project',
        statDeltas: [{ stat: 'intelligence', amount: 5 }, { stat: 'discipline', amount: 5 }, { stat: 'stress', amount: 10 }],
        flagChanges: [],
        outcome: 'You win first place. More importantly, your science teacher writes a letter to put in your file.',
      },
      {
        id: 'simple_safe',
        label: 'Do something simple and safe',
        statDeltas: [{ stat: 'intelligence', amount: 2 }, { stat: 'happiness', amount: 3 }],
        flagChanges: [],
        outcome: 'A working volcano. It\'s been done a thousand times, and it works fine.',
      },
    ],
  },
  {
    id: 'ch_chore_rebellion',
    title: 'The Chore Debate',
    description: 'Your parents assign you daily chores. It feels like they\'re running a small dictatorship.',
    stages: [LifeStage.Childhood],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'do_the_chores',
        label: 'Do the chores without complaint',
        statDeltas: [{ stat: 'discipline', amount: 5 }, { stat: 'happiness', amount: 2 }],
        flagChanges: [],
        outcome: 'Your parents trust you with more responsibility. Small habits, big patterns.',
      },
      {
        id: 'negotiate',
        label: 'Negotiate a chore allowance deal',
        statDeltas: [{ stat: 'charisma', amount: 4 }, { stat: 'intelligence', amount: 3 }],
        flagChanges: [],
        outcome: 'They accept your counter-offer. You\'ve just learned what negotiation tastes like.',
      },
    ],
  },
];
