import { LifeStage } from '@lifeverse/shared';
import type { GameEvent } from '@lifeverse/shared';

export const seniorEvents: GameEvent[] = [
  {
    id: 'sr_retirement_decision',
    title: 'The Last Day',
    description: 'Your colleagues have planned a retirement celebration. Decades of work end today — if you want them to.',
    stages: [LifeStage.Senior, LifeStage.Elder],
    statConditions: [],
    flagConditions: [{ key: 'isEmployed', value: true }, { key: 'isRetired', value: false }],
    weight: 3,
    cooldownYears: 99,
    choices: [
      {
        id: 'retire_now',
        label: 'Retire. You\'ve earned it.',
        statDeltas: [{ stat: 'happiness', amount: 8 }, { stat: 'stress', amount: -25 }, { stat: 'creativity', amount: 3 }],
        flagChanges: [{ key: 'isRetired', value: true }, { key: 'isEmployed', value: false }],
        outcome: 'The last day is both an ending and a door. You stand in front of it and breathe.',
      },
      {
        id: 'keep_working',
        label: 'Keep going — work gives you purpose',
        statDeltas: [{ stat: 'discipline', amount: 4 }, { stat: 'intelligence', amount: 3 }],
        flagChanges: [],
        outcome: 'The colleagues younger than you call it inspiring. You call it not being done yet.',
      },
    ],
  },
  {
    id: 'sr_grandchild',
    title: 'A New Person',
    description: 'Your child calls. You\'re going to be a grandparent.',
    stages: [LifeStage.Senior, LifeStage.Elder],
    statConditions: [],
    flagConditions: [{ key: 'hasChildren', value: true }],
    weight: 2,
    cooldownYears: 99,
    choices: [
      {
        id: 'fully_present',
        label: 'Be as present as you can in their early years',
        statDeltas: [{ stat: 'happiness', amount: 10 }, { stat: 'health', amount: 3 }, { stat: 'charisma', amount: 3 }],
        flagChanges: [{ key: 'isGrandparent', value: true }],
        outcome: 'You learn things about yourself you never knew. The smallest hands reveal the biggest things.',
      },
      {
        id: 'supportive_distance',
        label: 'Support from a distance — let the parents parent',
        statDeltas: [{ stat: 'happiness', amount: 6 }, { stat: 'intelligence', amount: 2 }],
        flagChanges: [{ key: 'isGrandparent', value: true }],
        outcome: 'Wise restraint. You\'re the refuge, not the second parent.',
      },
    ],
  },
  {
    id: 'sr_health_decline',
    title: 'The Appointment',
    description: 'Age is making itself known. The doctor lists some limitations. Your body is negotiating different terms now.',
    stages: [LifeStage.Senior, LifeStage.Elder],
    statConditions: [{ stat: 'health', operator: 'lte', value: 60 }],
    flagConditions: [],
    weight: 2,
    cooldownYears: 5,
    choices: [
      {
        id: 'take_it_seriously',
        label: 'Follow every recommendation strictly',
        statDeltas: [{ stat: 'health', amount: 5 }, { stat: 'discipline', amount: 5 }, { stat: 'happiness', amount: -2 }],
        flagChanges: [],
        outcome: 'Tedious, effective. You add years with discipline and a pill organiser.',
      },
      {
        id: 'adapt_and_accept',
        label: 'Accept some limitations and live fully within them',
        statDeltas: [{ stat: 'happiness', amount: 5 }, { stat: 'health', amount: 2 }, { stat: 'creativity', amount: 3 }],
        flagChanges: [],
        outcome: 'You find that working around a constraint opens unexpected doors.',
      },
    ],
  },
  {
    id: 'sr_estranged_family',
    title: 'The Phone Call',
    description: 'Someone you haven\'t spoken to in years calls out of nowhere. A family member you fell out with a long time ago.',
    stages: [LifeStage.Senior, LifeStage.Elder],
    statConditions: [],
    flagConditions: [],
    weight: 2,
    cooldownYears: 99,
    choices: [
      {
        id: 'reconcile',
        label: 'Listen and try to reconcile',
        statDeltas: [{ stat: 'happiness', amount: 8 }, { stat: 'charisma', amount: 4 }, { stat: 'stress', amount: -10 }],
        flagChanges: [],
        outcome: 'Old wounds close slowly but they close. You gain time you almost didn\'t have.',
      },
      {
        id: 'decline',
        label: 'Decline — some distances are healthier',
        statDeltas: [{ stat: 'discipline', amount: 3 }, { stat: 'happiness', amount: 3 }],
        flagChanges: [],
        outcome: 'Peace is not always found in reunion. You choose yours deliberately.',
      },
    ],
  },
  {
    id: 'sr_legacy_project',
    title: 'The Memoir',
    description: 'A younger family member asks you to write down your story. "Before we lose it," they say.',
    stages: [LifeStage.Senior, LifeStage.Elder],
    statConditions: [],
    flagConditions: [],
    weight: 2,
    cooldownYears: 99,
    choices: [
      {
        id: 'write_it',
        label: 'Write the memoir',
        statDeltas: [{ stat: 'creativity', amount: 6 }, { stat: 'happiness', amount: 7 }, { stat: 'intelligence', amount: 4 }],
        flagChanges: [],
        outcome: 'The writing teaches you what actually mattered. Some chapters surprise you.',
        seedsThreads: [{
          key: 'legacy_thread',
          category: 'generational',
          payload: { type: 'memoir' },
          triggerMinAge: 0,
          triggerMaxAge: 0,
          isGenerational: true,
        }],
      },
      {
        id: 'tell_it_in_person',
        label: 'Tell it in person, gathering the family',
        statDeltas: [{ stat: 'charisma', amount: 5 }, { stat: 'happiness', amount: 8 }],
        flagChanges: [],
        outcome: 'A dinner becomes a night that everyone present will talk about for decades.',
      },
    ],
  },
  {
    id: 'sr_young_mentor',
    title: 'The Protégé',
    description: 'A young person in your field asks if you\'d be willing to mentor them. They remind you of yourself.',
    stages: [LifeStage.Senior],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'accept',
        label: 'Say yes',
        statDeltas: [{ stat: 'charisma', amount: 4 }, { stat: 'happiness', amount: 6 }, { stat: 'intelligence', amount: 3 }],
        flagChanges: [],
        outcome: 'Teaching them teaches you. The best knowledge flows in both directions.',
      },
      {
        id: 'decline',
        label: 'Politely decline — your time is precious now',
        statDeltas: [{ stat: 'happiness', amount: 2 }],
        flagChanges: [],
        outcome: 'There is wisdom in knowing how to spend what\'s left of your time.',
      },
    ],
  },
  {
    id: 'sr_health_procedure',
    title: 'The Surgery',
    description: 'A procedure that could meaningfully extend your quality of life carries real risk at your age.',
    stages: [LifeStage.Senior, LifeStage.Elder],
    statConditions: [{ stat: 'health', operator: 'lte', value: 50 }],
    flagConditions: [],
    weight: 1,
    cooldownYears: 10,
    choices: [
      {
        id: 'proceed',
        label: 'Agree to the procedure',
        statDeltas: [{ stat: 'health', amount: 12 }, { stat: 'happiness', amount: 4 }, { stat: 'stress', amount: 15 }],
        flagChanges: [],
        outcome: 'A recovery that tests your patience. Then a year you wouldn\'t have had otherwise.',
      },
      {
        id: 'decline',
        label: 'Decline and manage it without surgery',
        statDeltas: [{ stat: 'happiness', amount: 3 }, { stat: 'stress', amount: -8 }],
        flagChanges: [],
        outcome: 'You choose quality over quantity. Fewer years, more on your own terms.',
      },
    ],
  },
  {
    id: 'sr_simplify_life',
    title: 'The Downsize',
    description: 'The family home is too large now. A smaller place would be cheaper and simpler. And harder to leave.',
    stages: [LifeStage.Senior, LifeStage.Elder],
    statConditions: [],
    flagConditions: [{ key: 'hasHouse', value: true }],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'downsize',
        label: 'Sell and downsize',
        statDeltas: [{ stat: 'happiness', amount: 4 }, { stat: 'stress', amount: -12 }, { stat: 'discipline', amount: 3 }],
        flagChanges: [],
        outcome: 'Letting go of things makes room for what\'s left. The smaller space somehow feels larger.',
      },
      {
        id: 'stay',
        label: 'Stay — the memories are in the walls',
        statDeltas: [{ stat: 'happiness', amount: 5 }],
        flagChanges: [],
        outcome: 'The house means too much. You keep it and the maintenance and the stairs.',
      },
    ],
  },
  {
    id: 'sr_life_review',
    title: 'The Long View',
    description: 'A quiet evening. A long life. The question comes without a knock: was it enough?',
    stages: [LifeStage.Senior, LifeStage.Elder],
    statConditions: [],
    flagConditions: [],
    weight: 2,
    cooldownYears: 10,
    choices: [
      {
        id: 'enough',
        label: 'Yes. Not perfect — but enough.',
        statDeltas: [{ stat: 'happiness', amount: 8 }, { stat: 'stress', amount: -15 }],
        flagChanges: [],
        outcome: 'Acceptance is not settling. It is the hardest and most honest form of courage.',
      },
      {
        id: 'one_more_thing',
        label: 'Not yet. There\'s one more thing.',
        statDeltas: [{ stat: 'discipline', amount: 5 }, { stat: 'creativity', amount: 5 }, { stat: 'happiness', amount: 4 }],
        flagChanges: [],
        outcome: 'You spend your remaining energy on the one thing you always meant to do. It is worth it.',
      },
      {
        id: 'regret',
        label: 'I wish I\'d done things differently.',
        statDeltas: [{ stat: 'happiness', amount: -5 }, { stat: 'intelligence', amount: 5 }],
        flagChanges: [],
        outcome: 'Regret, honestly felt, is not the same as despair. You let it teach you what still can be done.',
      },
    ],
  },
  {
    id: 'sr_partner_loss',
    title: 'The Empty Chair',
    description: 'Your partner is gone. The house is the same. Everything in it is different.',
    stages: [LifeStage.Senior, LifeStage.Elder],
    statConditions: [],
    flagConditions: [{ key: 'isMarried', value: true }],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'lean_on_family',
        label: 'Lean on family and friends',
        statDeltas: [{ stat: 'happiness', amount: -8 }, { stat: 'charisma', amount: 4 }, { stat: 'health', amount: -3 }],
        flagChanges: [{ key: 'isMarried', value: false }],
        outcome: 'Grief shared is grief carried. The people around you discover how much they need you too.',
      },
      {
        id: 'find_purpose',
        label: 'Pour yourself into something meaningful',
        statDeltas: [{ stat: 'happiness', amount: -5 }, { stat: 'creativity', amount: 6 }, { stat: 'discipline', amount: 5 }],
        flagChanges: [{ key: 'isMarried', value: false }],
        outcome: 'The something meaningful becomes a bridge from who you were to who you are now.',
      },
    ],
  },
];
