import { LifeStage } from '@lifeverse/shared';
import type { GameEvent } from '@lifeverse/shared';

export const youngAdultEvents: GameEvent[] = [
  {
    id: 'ya_university_choice',
    title: 'The Acceptance Letter',
    description: 'A university acceptance sits on the table. The tuition number underneath makes your stomach flip.',
    stages: [LifeStage.YoungAdult],
    statConditions: [],
    flagConditions: [{ key: 'hasDegree', value: false }, { key: 'planningUniversity', value: true }],
    weight: 3,
    cooldownYears: 99,
    choices: [
      {
        id: 'accept',
        label: 'Accept and take on the debt',
        statDeltas: [{ stat: 'intelligence', amount: 5 }, { stat: 'discipline', amount: 3 }, { stat: 'happiness', amount: 3 }],
        flagChanges: [{ key: 'inUniversity', value: true }],
        outcome: 'You sign. Four years of ideas, coffee, and debt begins today.',
      },
      {
        id: 'scholarship_hunt',
        label: 'Hunt for scholarships first',
        statDeltas: [{ stat: 'discipline', amount: 6 }, { stat: 'intelligence', amount: 4 }],
        flagChanges: [{ key: 'inUniversity', value: true }, { key: 'hasScholarship', value: true }],
        outcome: 'Three months of applications yield a partial scholarship. The grind already paid off.',
      },
      {
        id: 'defer',
        label: 'Defer for a year and work',
        statDeltas: [{ stat: 'discipline', amount: 4 }, { stat: 'happiness', amount: 3 }],
        flagChanges: [],
        outcome: 'A gap year filled with work and real experience. University can wait.',
      },
    ],
  },
  {
    id: 'ya_first_real_job',
    title: 'The Offer',
    description: 'After months of applications, a job offer lands in your inbox. Entry-level, real salary, real responsibility.',
    stages: [LifeStage.YoungAdult],
    statConditions: [],
    flagConditions: [{ key: 'isEmployed', value: false }, { key: 'hasDegree', value: true }],
    weight: 3,
    cooldownYears: 99,
    choices: [
      {
        id: 'take_it',
        label: 'Accept immediately',
        statDeltas: [{ stat: 'discipline', amount: 4 }, { stat: 'happiness', amount: 5 }],
        flagChanges: [{ key: 'isEmployed', value: true }],
        outcome: 'First day nerves, first paycheck relief. The working world is yours now.',
      },
      {
        id: 'negotiate',
        label: 'Negotiate the salary first',
        statDeltas: [{ stat: 'charisma', amount: 5 }, { stat: 'discipline', amount: 3 }, { stat: 'happiness', amount: 4 }],
        flagChanges: [{ key: 'isEmployed', value: true }],
        outcome: 'They come up by $4,000. You learned today that asking is free.',
      },
    ],
  },
  {
    id: 'ya_startup_idea',
    title: 'The Idea',
    description: 'At 2am over cheap noodles, you and a friend sketch out a business idea that could actually work.',
    stages: [LifeStage.YoungAdult],
    statConditions: [{ stat: 'creativity', operator: 'gte', value: 55 }, { stat: 'intelligence', operator: 'gte', value: 55 }],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'pursue',
        label: 'Quit your job and pursue it',
        statDeltas: [{ stat: 'discipline', amount: 6 }, { stat: 'creativity', amount: 6 }, { stat: 'happiness', amount: 4 }, { stat: 'stress', amount: 20 }],
        flagChanges: [{ key: 'isEntrepreneur', value: true }, { key: 'isEmployed', value: false }],
        outcome: 'You burn your safety net. Now you have no choice but to build something.',
        seedsThreads: [{
          key: 'startup_thread',
          category: 'career',
          payload: { founded: true },
          triggerMinAge: 26,
          triggerMaxAge: 40,
        }],
      },
      {
        id: 'side_project',
        label: 'Build it on the side while keeping your job',
        statDeltas: [{ stat: 'discipline', amount: 5 }, { stat: 'creativity', amount: 4 }, { stat: 'stress', amount: 12 }],
        flagChanges: [{ key: 'hasSideProject', value: true }],
        outcome: 'Less risk, less speed. You build slowly but you keep the lights on.',
      },
      {
        id: 'sleep_on_it',
        label: 'Sleep on it and never revisit it',
        statDeltas: [{ stat: 'happiness', amount: -2 }],
        flagChanges: [],
        outcome: 'A year later someone else launches something very similar. You read about it on the train.',
      },
    ],
  },
  {
    id: 'ya_first_apartment',
    title: 'Your Own Place',
    description: 'You find an apartment you can barely afford. It\'s small. It\'s perfect. It\'s yours.',
    stages: [LifeStage.YoungAdult],
    statConditions: [],
    flagConditions: [{ key: 'isEmployed', value: true }],
    weight: 2,
    cooldownYears: 99,
    choices: [
      {
        id: 'go_solo',
        label: 'Live alone — value your independence',
        statDeltas: [{ stat: 'discipline', amount: 4 }, { stat: 'happiness', amount: 5 }, { stat: 'intelligence', amount: 3 }],
        flagChanges: [],
        outcome: 'Silence. Your own choices. Slightly cold leftovers. You love it.',
      },
      {
        id: 'get_roommates',
        label: 'Get roommates to split costs',
        statDeltas: [{ stat: 'charisma', amount: 5 }, { stat: 'happiness', amount: 4 }],
        flagChanges: [],
        outcome: 'The kitchen is a democracy and the bathroom is contested territory. Worth it.',
      },
    ],
  },
  {
    id: 'ya_heartbreak',
    title: 'The End',
    description: 'Your relationship ends. The reasons are real and complicated and don\'t make it hurt less.',
    stages: [LifeStage.YoungAdult],
    statConditions: [],
    flagConditions: [{ key: 'hasPartner', value: true }],
    weight: 2,
    cooldownYears: 99,
    choices: [
      {
        id: 'process_it',
        label: 'Take time to actually grieve it',
        statDeltas: [{ stat: 'happiness', amount: -7 }, { stat: 'intelligence', amount: 4 }, { stat: 'creativity', amount: 5 }],
        flagChanges: [{ key: 'hasPartner', value: false }],
        outcome: 'You learn more about yourself in the wreckage than you did in the relationship.',
      },
      {
        id: 'rebound',
        label: 'Distract yourself with someone new',
        statDeltas: [{ stat: 'happiness', amount: -2 }, { stat: 'charisma', amount: 3 }],
        flagChanges: [{ key: 'hasPartner', value: false }],
        outcome: 'It doesn\'t work the way you hoped. But you\'re not alone, which is something.',
      },
    ],
  },
  {
    id: 'ya_travel_opportunity',
    title: 'The Road',
    description: 'A friend proposes a month-long trip abroad. Your boss says you can take the time — but it\'s unpaid.',
    stages: [LifeStage.YoungAdult],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'go',
        label: 'Go. You\'ll figure out the money.',
        statDeltas: [{ stat: 'charisma', amount: 5 }, { stat: 'creativity', amount: 5 }, { stat: 'happiness', amount: 7 }, { stat: 'intelligence', amount: 3 }],
        flagChanges: [],
        outcome: 'You return broke and larger. No amount of saving would have bought what you learned.',
      },
      {
        id: 'stay',
        label: 'Stay and save the money',
        statDeltas: [{ stat: 'discipline', amount: 4 }],
        flagChanges: [],
        outcome: 'Responsible. You watch your savings account grow and your friend\'s photos flood your feed.',
      },
    ],
  },
  {
    id: 'ya_ethical_dilemma',
    title: 'The Shortcut',
    description: 'A colleague tells you about an easy way to get ahead at work. It\'s not illegal. It might not be right.',
    stages: [LifeStage.YoungAdult],
    statConditions: [],
    flagConditions: [{ key: 'isEmployed', value: true }],
    weight: 1,
    cooldownYears: 5,
    choices: [
      {
        id: 'take_shortcut',
        label: 'Use the shortcut',
        statDeltas: [{ stat: 'charisma', amount: 3 }, { stat: 'discipline', amount: -3 }, { stat: 'happiness', amount: -2 }],
        flagChanges: [],
        outcome: 'It works. For now. You notice you don\'t like the person who did that.',
        seedsThreads: [{
          key: 'integrity_thread',
          category: 'career',
          payload: { shortcutTaken: true },
          triggerMinAge: 30,
          triggerMaxAge: 45,
        }],
      },
      {
        id: 'decline',
        label: 'Do it the right way',
        statDeltas: [{ stat: 'discipline', amount: 5 }, { stat: 'intelligence', amount: 3 }, { stat: 'happiness', amount: 3 }],
        flagChanges: [],
        outcome: 'Slower. Worth it. You look in the mirror without hesitation.',
      },
    ],
  },
  {
    id: 'ya_grad_school',
    title: 'Go Deeper',
    description: 'Your undergraduate professor suggests graduate school. "You could go further," she says.',
    stages: [LifeStage.YoungAdult],
    statConditions: [{ stat: 'intelligence', operator: 'gte', value: 65 }],
    flagConditions: [{ key: 'hasDegree', value: true }],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'apply',
        label: 'Apply for graduate school',
        statDeltas: [{ stat: 'intelligence', amount: 7 }, { stat: 'discipline', amount: 5 }, { stat: 'stress', amount: 15 }],
        flagChanges: [{ key: 'inGradSchool', value: true }],
        outcome: 'The work is harder and the conversations are better. You are operating at the frontier.',
      },
      {
        id: 'work_instead',
        label: 'Get experience in the real world',
        statDeltas: [{ stat: 'discipline', amount: 4 }, { stat: 'charisma', amount: 4 }],
        flagChanges: [],
        outcome: 'Theory and practice are different muscles. You choose the one the classroom can\'t train.',
      },
    ],
  },
  {
    id: 'ya_networking_event',
    title: 'The Room',
    description: 'You\'re at a professional event. Everyone is handing out cards. A very senior person sits down next to you.',
    stages: [LifeStage.YoungAdult],
    statConditions: [],
    flagConditions: [],
    weight: 1,
    cooldownYears: 4,
    choices: [
      {
        id: 'engage',
        label: 'Start a genuine conversation',
        statDeltas: [{ stat: 'charisma', amount: 5 }, { stat: 'intelligence', amount: 3 }, { stat: 'happiness', amount: 3 }],
        flagChanges: [],
        outcome: 'They remember your name. That is worth more than a hundred résumés.',
      },
      {
        id: 'elevator_pitch',
        label: 'Launch into your practised pitch',
        statDeltas: [{ stat: 'charisma', amount: 2 }, { stat: 'discipline', amount: 2 }],
        flagChanges: [],
        outcome: 'They nod politely. You\'re forgettable. The pitch needed more genuine curiosity.',
      },
    ],
  },
  {
    id: 'ya_bad_boss',
    title: 'The Manager',
    description: 'Your manager takes credit for your work in a meeting. In front of everyone. You watch it happen.',
    stages: [LifeStage.YoungAdult],
    statConditions: [],
    flagConditions: [{ key: 'isEmployed', value: true }],
    weight: 1,
    cooldownYears: 5,
    choices: [
      {
        id: 'confront',
        label: 'Address it with them directly, privately',
        statDeltas: [{ stat: 'charisma', amount: 5 }, { stat: 'discipline', amount: 4 }, { stat: 'stress', amount: 10 }],
        flagChanges: [],
        outcome: 'They apologise awkwardly. Nothing changes, but you know you won\'t be pushed around.',
      },
      {
        id: 'document_and_wait',
        label: 'Document everything and watch for patterns',
        statDeltas: [{ stat: 'intelligence', amount: 4 }, { stat: 'discipline', amount: 3 }],
        flagChanges: [],
        outcome: 'You build a paper trail quietly. The pattern continues. Now you have evidence.',
      },
      {
        id: 'quit',
        label: 'Start looking for a new job',
        statDeltas: [{ stat: 'charisma', amount: 3 }, { stat: 'happiness', amount: 3 }, { stat: 'discipline', amount: 3 }],
        flagChanges: [],
        outcome: 'Life is too short for bad management. You find something better within four months.',
      },
    ],
  },
  {
    id: 'ya_investment_chance',
    title: 'The Opportunity',
    description: 'A friend in finance tells you about a small company that looks undervalued. It\'s not a sure thing.',
    stages: [LifeStage.YoungAdult],
    statConditions: [],
    flagConditions: [{ key: 'isEmployed', value: true }],
    weight: 1,
    cooldownYears: 5,
    choices: [
      {
        id: 'invest_big',
        label: 'Put in a meaningful amount',
        statDeltas: [{ stat: 'intelligence', amount: 4 }, { stat: 'happiness', amount: 2 }, { stat: 'stress', amount: 10 }],
        flagChanges: [],
        outcome: 'It triples in two years. You learn that calculated risk is a skill, not just luck.',
      },
      {
        id: 'invest_small',
        label: 'Invest a small amount to test the waters',
        statDeltas: [{ stat: 'intelligence', amount: 3 }, { stat: 'discipline', amount: 2 }],
        flagChanges: [],
        outcome: 'It works out. The cautious bet was still a bet. Good habit forming.',
      },
      {
        id: 'pass',
        label: 'Too risky — keep savings safe',
        statDeltas: [{ stat: 'discipline', amount: 3 }],
        flagChanges: [],
        outcome: 'Probably wise. Patience is also a strategy.',
      },
    ],
  },
  {
    id: 'ya_creative_breakthrough',
    title: 'The Spark',
    description: 'An idea arrives fully formed at 3am. You know, somehow, that it\'s the best thing you\'ve ever thought of.',
    stages: [LifeStage.YoungAdult],
    statConditions: [{ stat: 'creativity', operator: 'gte', value: 60 }],
    flagConditions: [],
    weight: 1,
    cooldownYears: 99,
    choices: [
      {
        id: 'act_now',
        label: 'Get up and start working on it immediately',
        statDeltas: [{ stat: 'creativity', amount: 7 }, { stat: 'discipline', amount: 5 }, { stat: 'health', amount: -2 }],
        flagChanges: [],
        outcome: 'By dawn you have the bones of something real. Sleep-deprived and certain.',
      },
      {
        id: 'note_and_sleep',
        label: 'Write it down and sleep on it',
        statDeltas: [{ stat: 'creativity', amount: 4 }, { stat: 'intelligence', amount: 3 }, { stat: 'health', amount: 2 }],
        flagChanges: [],
        outcome: 'Rested and fresh in the morning, you build on it with a clear head.',
      },
    ],
  },
];
