import { LifeStage } from '@lifeverse/shared';
import type { ActivityDefinition } from '@lifeverse/shared';

export const adolescenceActivities: ActivityDefinition[] = [
  {
    id: 'teen_intensive_study',
    label: 'Intensive Studying',
    description: 'Push hard. Exam prep, advanced coursework, tutoring yourself to the top.',
    domain: 'academic',
    timeCost: 2,
    mentalCost: 25,
    burnoutRisk: 0.15,
    statDeltas: [{ stat: 'intelligence', amount: 6 }, { stat: 'discipline', amount: 4 }],
    domainGains: [{ domain: 'academic', amount: 8 }],
    stages: [LifeStage.Adolescence],
    weight: 2,
    tags: ['school', 'cognitive', 'high-effort'],
  },
  {
    id: 'teen_part_time_job',
    label: 'Take a Part-Time Job',
    description: 'Stack shelves, serve tables, answer phones. The first paycheck changes something in you.',
    domain: 'career',
    timeCost: 2,
    statDeltas: [{ stat: 'discipline', amount: 4 }, { stat: 'charisma', amount: 2 }],
    domainGains: [{ domain: 'career', amount: 6 }],
    stages: [LifeStage.Adolescence],
    blockedFlags: ['isEmployed'],
    weight: 2,
    tags: ['work', 'money', 'discipline'],
  },
  {
    id: 'teen_social_hangout',
    label: 'Social Life',
    description: 'Parties, hangouts, the cafeteria, Friday nights. Build your social world.',
    domain: 'social',
    timeCost: 1,
    statDeltas: [{ stat: 'charisma', amount: 3 }, { stat: 'happiness', amount: 4 }],
    domainGains: [{ domain: 'social', amount: 5 }],
    stages: [LifeStage.Adolescence],
    weight: 2,
    tags: ['social', 'fun'],
  },
  {
    id: 'teen_exercise',
    label: 'Exercise Routine',
    description: 'Morning runs, push-ups, the weight room. Building a body that lasts.',
    domain: 'physical',
    timeCost: 1,
    physicalCost: 15,
    statDeltas: [{ stat: 'health', amount: 4 }, { stat: 'discipline', amount: 3 }],
    domainGains: [{ domain: 'physical', amount: 6 }],
    stages: [LifeStage.Adolescence],
    weight: 2,
    tags: ['health', 'discipline'],
  },
  {
    id: 'teen_creative_project',
    label: 'Creative Project',
    description: 'A band, a zine, a short film, a novel draft. Something yours, something real.',
    domain: 'creative',
    timeCost: 2,
    mentalCost: 20,
    statDeltas: [{ stat: 'creativity', amount: 6 }, { stat: 'intelligence', amount: 3 }],
    domainGains: [{ domain: 'creative', amount: 7 }],
    stages: [LifeStage.Adolescence],
    weight: 1,
    tags: ['creative', 'cognitive'],
  },
  {
    id: 'teen_volunteer',
    label: 'Volunteer Work',
    description: 'Community service, local charities, helping where needed. Doing good is its own reward.',
    domain: 'social',
    secondaryDomain: 'career',
    timeCost: 1,
    statDeltas: [{ stat: 'charisma', amount: 3 }, { stat: 'discipline', amount: 3 }],
    domainGains: [{ domain: 'social', amount: 5 }, { domain: 'career', amount: 3 }],
    stages: [LifeStage.Adolescence],
    weight: 1,
    tags: ['social', 'discipline'],
  },
  {
    id: 'teen_self_study',
    label: 'Self-Directed Learning',
    description: 'Online courses, documentaries, Wikipedia rabbit holes. Learning beyond the syllabus.',
    domain: 'academic',
    timeCost: 1,
    mentalCost: 15,
    statDeltas: [{ stat: 'intelligence', amount: 3 }],
    domainGains: [{ domain: 'academic', amount: 4 }],
    stages: [LifeStage.Adolescence],
    weight: 2,
    tags: ['cognitive'],
  },
  {
    id: 'teen_competitive_sport',
    label: 'Competitive Sport',
    description: 'Training, tournaments, pressure. Sport at this level builds a different kind of strength.',
    domain: 'physical',
    timeCost: 1,
    physicalCost: 12,
    statDeltas: [{ stat: 'health', amount: 3 }, { stat: 'discipline', amount: 4 }],
    domainGains: [{ domain: 'physical', amount: 5 }],
    stages: [LifeStage.Adolescence],
    minDomainLevel: { physical: 20 },
    weight: 1,
    tags: ['health', 'discipline', 'competitive'],
  },
  {
    id: 'teen_rest',
    label: 'Rest and Recharge',
    description: 'Sleep in. Binge something mindless. Let the week wash off.',
    domain: 'mental',
    timeCost: 1,
    statDeltas: [{ stat: 'happiness', amount: 2 }],
    domainGains: [{ domain: 'mental', amount: 3 }],
    energyRestore: { mental: 25, physical: 20 },
    stages: [LifeStage.Adolescence],
    weight: 1,
    tags: ['rest', 'recovery'],
  },
  {
    id: 'teen_explore_passions',
    label: 'Explore Creative Passions',
    description: 'Try everything. Art, music, coding, writing — find the thing that pulls you.',
    domain: 'creative',
    secondaryDomain: 'social',
    timeCost: 1,
    mentalCost: 10,
    statDeltas: [{ stat: 'creativity', amount: 4 }, { stat: 'charisma', amount: 2 }],
    domainGains: [{ domain: 'creative', amount: 4 }, { domain: 'social', amount: 3 }],
    stages: [LifeStage.Adolescence],
    minDomainLevel: { creative: 15 },
    weight: 1,
    tags: ['creative', 'social'],
  },
];
