import { LifeStage } from '@lifeverse/shared';
import type { ActivityDefinition } from '@lifeverse/shared';

export const adultActivities: ActivityDefinition[] = [
  {
    id: 'a_work_overtime',
    label: 'Work Overtime',
    description: 'Grind harder than everyone else. The career advances, but something costs.',
    domain: 'career',
    timeCost: 1,
    mentalCost: 20,
    burnoutRisk: 0.3,
    statDeltas: [{ stat: 'discipline', amount: 4 }],
    domainGains: [{ domain: 'career', amount: 7 }],
    stages: [LifeStage.Adult],
    requiredFlags: ['isEmployed'],
    weight: 2,
    tags: ['career', 'high-effort'],
  },
  {
    id: 'a_family_time',
    label: 'Quality Family Time',
    description: 'Dinner without phones. Weekend adventures. The small moments that are actually the big ones.',
    domain: 'social',
    secondaryDomain: 'mental',
    timeCost: 1,
    statDeltas: [{ stat: 'happiness', amount: 5 }],
    domainGains: [{ domain: 'social', amount: 7 }, { domain: 'mental', amount: 5 }],
    energyRestore: { mental: 10 },
    stages: [LifeStage.Adult],
    requiredFlags: ['hasChildren'],
    weight: 2,
    tags: ['social', 'emotional'],
  },
  {
    id: 'a_family_time_partner',
    label: 'Partner Quality Time',
    description: 'Date nights, real conversations, building a life together instead of just in parallel.',
    domain: 'social',
    secondaryDomain: 'mental',
    timeCost: 1,
    statDeltas: [{ stat: 'happiness', amount: 4 }],
    domainGains: [{ domain: 'social', amount: 5 }, { domain: 'mental', amount: 4 }],
    energyRestore: { mental: 8 },
    stages: [LifeStage.Adult],
    requiredFlags: ['isMarried'],
    weight: 2,
    tags: ['social', 'emotional'],
  },
  {
    id: 'a_fitness',
    label: 'Fitness Routine',
    description: 'The discipline to exercise when you have a mortgage and a job takes real character.',
    domain: 'physical',
    timeCost: 1,
    physicalCost: 20,
    statDeltas: [{ stat: 'health', amount: 5 }, { stat: 'discipline', amount: 3 }],
    domainGains: [{ domain: 'physical', amount: 6 }],
    stages: [LifeStage.Adult],
    weight: 2,
    tags: ['health', 'discipline'],
  },
  {
    id: 'a_therapy',
    label: 'Therapy',
    description: 'Professional help. The most effective performance enhancement most people never try.',
    domain: 'mental',
    timeCost: 1,
    moneyCost: 1500,
    statDeltas: [{ stat: 'happiness', amount: 5 }],
    domainGains: [{ domain: 'mental', amount: 8 }],
    energyRestore: { mental: 35 },
    statDeltasOverride: [{ stat: 'stress', amount: -10 }],
    stages: [LifeStage.Adult],
    weight: 1,
    tags: ['mental', 'recovery'],
  },
  {
    id: 'a_community_leadership',
    label: 'Community Leadership',
    description: 'Lead a committee. Run a local initiative. Build something beyond your immediate circle.',
    domain: 'social',
    timeCost: 1,
    statDeltas: [{ stat: 'charisma', amount: 5 }],
    domainGains: [{ domain: 'social', amount: 8 }],
    stages: [LifeStage.Adult],
    minDomainLevel: { social: 40 },
    weight: 1,
    tags: ['social', 'leadership'],
  },
  {
    id: 'a_career_development',
    label: 'Career Development',
    description: 'Courses, certifications, professional development. Staying sharp in a world that moves fast.',
    domain: 'academic',
    secondaryDomain: 'career',
    timeCost: 1,
    mentalCost: 15,
    moneyCost: 1000,
    statDeltas: [{ stat: 'intelligence', amount: 3 }],
    domainGains: [{ domain: 'academic', amount: 4 }, { domain: 'career', amount: 7 }],
    stages: [LifeStage.Adult],
    weight: 2,
    tags: ['cognitive', 'career'],
  },
  {
    id: 'a_creative_hobby',
    label: 'Creative Hobby',
    description: 'The thing you do for yourself alone. Cooking, painting, music, woodworking.',
    domain: 'creative',
    timeCost: 1,
    mentalCost: 15,
    statDeltas: [{ stat: 'creativity', amount: 5 }, { stat: 'happiness', amount: 4 }],
    domainGains: [{ domain: 'creative', amount: 6 }],
    stages: [LifeStage.Adult],
    weight: 2,
    tags: ['creative', 'fun'],
  },
  {
    id: 'a_invest_learn',
    label: 'Investment Learning',
    description: 'Read the books your broker wishes you would not. Understand where your money is going.',
    domain: 'academic',
    timeCost: 1,
    mentalCost: 15,
    moneyCost: 2000,
    statDeltas: [{ stat: 'intelligence', amount: 4 }],
    domainGains: [{ domain: 'academic', amount: 5 }],
    stages: [LifeStage.Adult],
    minDomainLevel: { academic: 30 },
    weight: 1,
    tags: ['cognitive', 'finance'],
  },
  {
    id: 'a_staycation',
    label: 'Real Vacation',
    description: 'Two weeks off. No email. No "just checking in." Actual disconnection.',
    domain: 'mental',
    timeCost: 2,
    statDeltas: [{ stat: 'happiness', amount: 5 }],
    domainGains: [{ domain: 'mental', amount: 7 }],
    energyRestore: { mental: 40, physical: 35 },
    statDeltasOverride: [{ stat: 'stress', amount: -12 }],
    stages: [LifeStage.Adult],
    weight: 1,
    tags: ['rest', 'recovery'],
  },
  {
    id: 'a_mentor_others',
    label: 'Mentor Junior Colleagues',
    description: 'Teaching is the best way to learn what you actually know.',
    domain: 'social',
    secondaryDomain: 'career',
    timeCost: 1,
    statDeltas: [{ stat: 'charisma', amount: 5 }],
    domainGains: [{ domain: 'social', amount: 6 }, { domain: 'career', amount: 5 }],
    stages: [LifeStage.Adult],
    minDomainLevel: { career: 50, social: 40 },
    weight: 1,
    tags: ['social', 'leadership', 'career'],
  },
  {
    id: 'a_side_business',
    label: 'Build a Side Business',
    description: 'The idea you have been sitting on for five years. This year you build it on weekends.',
    domain: 'career',
    secondaryDomain: 'creative',
    timeCost: 2,
    mentalCost: 25,
    burnoutRisk: 0.35,
    statDeltas: [{ stat: 'discipline', amount: 6 }],
    domainGains: [{ domain: 'career', amount: 8 }, { domain: 'creative', amount: 5 }],
    stages: [LifeStage.Adult],
    minDomainLevel: { career: 40, creative: 35 },
    weight: 1,
    tags: ['career', 'creative', 'high-effort'],
  },
  {
    id: 'a_health_focus',
    label: 'Health-First Year',
    description: 'Sleep schedule, diet, regular GP visits, the things adults ignore until they cannot.',
    domain: 'physical',
    secondaryDomain: 'mental',
    timeCost: 1,
    physicalCost: 15,
    statDeltas: [{ stat: 'health', amount: 5 }],
    domainGains: [{ domain: 'physical', amount: 6 }, { domain: 'mental', amount: 3 }],
    stages: [LifeStage.Adult],
    weight: 2,
    tags: ['health', 'recovery'],
  },
  {
    id: 'a_reflection',
    label: 'Reflection and Life Planning',
    description: 'A weekend alone with your thoughts and a notebook. Rare. Essential.',
    domain: 'mental',
    secondaryDomain: 'academic',
    timeCost: 1,
    mentalCost: 10,
    statDeltas: [{ stat: 'intelligence', amount: 3 }],
    domainGains: [{ domain: 'mental', amount: 6 }],
    energyRestore: { mental: 15 },
    stages: [LifeStage.Adult],
    weight: 1,
    tags: ['mental', 'cognitive'],
  },
];
