import { LifeStage } from '@lifeverse/shared';
import type { ActivityDefinition } from '@lifeverse/shared';

export const childhoodActivities: ActivityDefinition[] = [
  {
    id: 'ch_study_hard',
    label: 'Study Hard',
    description: 'Hit the books. Extra homework and practice problems sharpen your young mind.',
    domain: 'academic',
    timeCost: 1,
    mentalCost: 15,
    statDeltas: [{ stat: 'intelligence', amount: 3 }, { stat: 'discipline', amount: 2 }],
    domainGains: [{ domain: 'academic', amount: 5 }],
    stages: [LifeStage.Childhood],
    weight: 2,
    tags: ['school', 'cognitive'],
  },
  {
    id: 'ch_play_outside',
    label: 'Play Outside',
    description: 'Run, climb, explore. Your body is growing and it needs movement.',
    domain: 'physical',
    timeCost: 1,
    physicalCost: 10,
    statDeltas: [{ stat: 'health', amount: 3 }, { stat: 'happiness', amount: 3 }],
    domainGains: [{ domain: 'physical', amount: 4 }],
    stages: [LifeStage.Childhood],
    weight: 2,
    tags: ['health', 'fun'],
  },
  {
    id: 'ch_read_books',
    label: 'Read for Fun',
    description: 'Stories, science, adventure — books open doors your school never shows you.',
    domain: 'academic',
    secondaryDomain: 'creative',
    timeCost: 1,
    mentalCost: 10,
    statDeltas: [{ stat: 'intelligence', amount: 2 }, { stat: 'creativity', amount: 2 }],
    domainGains: [{ domain: 'academic', amount: 3 }, { domain: 'creative', amount: 2 }],
    stages: [LifeStage.Childhood],
    weight: 2,
    tags: ['cognitive', 'creative'],
  },
  {
    id: 'ch_practice_hobby',
    label: 'Develop a Hobby',
    description: 'Drawing, building, music — pick something and do it until it becomes part of you.',
    domain: 'creative',
    timeCost: 1,
    mentalCost: 10,
    statDeltas: [{ stat: 'creativity', amount: 4 }, { stat: 'happiness', amount: 3 }],
    domainGains: [{ domain: 'creative', amount: 5 }],
    stages: [LifeStage.Childhood],
    weight: 2,
    tags: ['creative', 'fun'],
  },
  {
    id: 'ch_play_with_friends',
    label: 'Hang Out with Friends',
    description: 'Friendships forged young run deep. Show up and be present.',
    domain: 'social',
    timeCost: 1,
    statDeltas: [{ stat: 'charisma', amount: 2 }, { stat: 'happiness', amount: 3 }],
    domainGains: [{ domain: 'social', amount: 4 }],
    stages: [LifeStage.Childhood],
    weight: 2,
    tags: ['social', 'fun'],
  },
  {
    id: 'ch_family_time',
    label: 'Quality Family Time',
    description: 'Dinner conversations, board games, stories before bed. Simple moments that root you.',
    domain: 'mental',
    secondaryDomain: 'social',
    timeCost: 1,
    statDeltas: [{ stat: 'happiness', amount: 4 }],
    domainGains: [{ domain: 'mental', amount: 4 }, { domain: 'social', amount: 3 }],
    energyRestore: { mental: 10 },
    stages: [LifeStage.Childhood],
    weight: 2,
    tags: ['social', 'emotional'],
  },
  {
    id: 'ch_sports_team',
    label: 'Join a Sports Team',
    description: 'Discipline, teamwork, sweat. A sport is a school the classroom never offers.',
    domain: 'physical',
    secondaryDomain: 'social',
    timeCost: 1,
    physicalCost: 15,
    statDeltas: [{ stat: 'health', amount: 4 }, { stat: 'discipline', amount: 3 }],
    domainGains: [{ domain: 'physical', amount: 5 }, { domain: 'social', amount: 3 }],
    stages: [LifeStage.Childhood],
    weight: 1,
    tags: ['health', 'social', 'discipline'],
  },
  {
    id: 'ch_rest_day',
    label: 'Rest and Recharge',
    description: 'Do nothing productive. Let your mind and body reset. This is also a skill.',
    domain: 'mental',
    timeCost: 1,
    statDeltas: [{ stat: 'happiness', amount: 2 }],
    domainGains: [{ domain: 'mental', amount: 2 }],
    energyRestore: { mental: 20, physical: 20 },
    stages: [LifeStage.Childhood],
    weight: 1,
    tags: ['rest', 'recovery'],
  },
];
