import { LifeStage } from '@lifeverse/shared';
import type { ActivityDefinition } from '@lifeverse/shared';

export const seniorActivities: ActivityDefinition[] = [
  {
    id: 'sr_gentle_exercise',
    label: 'Gentle Exercise',
    description: 'Walking, swimming, yoga, tai chi. Keep the body moving on its own terms.',
    domain: 'physical',
    timeCost: 1,
    physicalCost: 10,
    statDeltas: [{ stat: 'health', amount: 4 }, { stat: 'happiness', amount: 3 }],
    domainGains: [{ domain: 'physical', amount: 5 }],
    stages: [LifeStage.Senior, LifeStage.Elder],
    weight: 2,
    tags: ['health', 'gentle'],
  },
  {
    id: 'sr_grandchild_time',
    label: 'Time with Grandchildren',
    description: 'The second chance childhood. Show up differently than you did the first time.',
    domain: 'social',
    secondaryDomain: 'mental',
    timeCost: 1,
    statDeltas: [{ stat: 'happiness', amount: 8 }],
    domainGains: [{ domain: 'social', amount: 6 }, { domain: 'mental', amount: 5 }],
    energyRestore: { mental: 15 },
    stages: [LifeStage.Senior, LifeStage.Elder],
    requiredFlags: ['isGrandparent'],
    weight: 2,
    tags: ['social', 'emotional'],
  },
  {
    id: 'sr_memoir',
    label: 'Write Your Memoir',
    description: 'Your life has earned a story. Begin writing it before time forgets the details.',
    domain: 'creative',
    secondaryDomain: 'academic',
    timeCost: 2,
    mentalCost: 15,
    statDeltas: [{ stat: 'creativity', amount: 7 }, { stat: 'intelligence', amount: 4 }],
    domainGains: [{ domain: 'creative', amount: 8 }, { domain: 'academic', amount: 4 }],
    stages: [LifeStage.Senior, LifeStage.Elder],
    weight: 1,
    tags: ['creative', 'cognitive', 'legacy'],
  },
  {
    id: 'sr_community_wisdom',
    label: 'Share Community Wisdom',
    description: 'Speak at local events. Mentor the young. Your experience is the most underrated resource.',
    domain: 'social',
    timeCost: 1,
    statDeltas: [{ stat: 'charisma', amount: 5 }],
    domainGains: [{ domain: 'social', amount: 7 }],
    stages: [LifeStage.Senior, LifeStage.Elder],
    minDomainLevel: { social: 50 },
    weight: 1,
    tags: ['social', 'leadership', 'legacy'],
  },
  {
    id: 'sr_learn_new_skill',
    label: 'Learn Something New',
    description: 'A language, a technology, an instrument. The brain grows when you challenge it.',
    domain: 'academic',
    secondaryDomain: 'creative',
    timeCost: 1,
    mentalCost: 15,
    statDeltas: [{ stat: 'intelligence', amount: 4 }, { stat: 'creativity', amount: 4 }],
    domainGains: [{ domain: 'academic', amount: 5 }, { domain: 'creative', amount: 4 }],
    stages: [LifeStage.Senior, LifeStage.Elder],
    weight: 2,
    tags: ['cognitive', 'creative'],
  },
  {
    id: 'sr_health_maintenance',
    label: 'Active Health Management',
    description: 'Doctor visits, prescriptions, dietary discipline. Prevention is far cheaper than cure.',
    domain: 'physical',
    secondaryDomain: 'mental',
    timeCost: 1,
    moneyCost: 500,
    statDeltas: [{ stat: 'health', amount: 5 }],
    domainGains: [{ domain: 'physical', amount: 4 }, { domain: 'mental', amount: 3 }],
    stages: [LifeStage.Senior, LifeStage.Elder],
    weight: 2,
    tags: ['health', 'maintenance'],
  },
  {
    id: 'sr_deep_rest',
    label: 'Deep Rest',
    description: 'You have earned it. Proper sleep, no schedule, slow mornings.',
    domain: 'mental',
    timeCost: 1,
    statDeltas: [{ stat: 'happiness', amount: 5 }],
    domainGains: [{ domain: 'mental', amount: 7 }],
    energyRestore: { mental: 40, physical: 30 },
    statDeltasOverride: [{ stat: 'stress', amount: -15 }],
    stages: [LifeStage.Senior, LifeStage.Elder],
    weight: 2,
    tags: ['rest', 'recovery'],
  },
  {
    id: 'sr_travel',
    label: 'Travel While You Can',
    description: 'The destinations you promised yourself. Knees and schedules permitting.',
    domain: 'social',
    secondaryDomain: 'creative',
    timeCost: 2,
    moneyCost: 4000,
    statDeltas: [{ stat: 'happiness', amount: 7 }, { stat: 'charisma', amount: 4 }],
    domainGains: [{ domain: 'social', amount: 5 }, { domain: 'creative', amount: 4 }],
    stages: [LifeStage.Senior, LifeStage.Elder],
    weight: 1,
    tags: ['social', 'creative', 'expensive'],
  },
  {
    id: 'sr_legacy_project',
    label: 'Legacy Creative Project',
    description: 'The thing you will be remembered for. Not for legacy — for love of the work.',
    domain: 'creative',
    secondaryDomain: 'social',
    timeCost: 2,
    mentalCost: 20,
    statDeltas: [{ stat: 'creativity', amount: 8 }, { stat: 'charisma', amount: 5 }],
    domainGains: [{ domain: 'creative', amount: 9 }, { domain: 'social', amount: 5 }],
    stages: [LifeStage.Senior, LifeStage.Elder],
    minDomainLevel: { creative: 50 },
    weight: 1,
    tags: ['creative', 'legacy'],
  },
];
