import { LifeStage } from '@lifeverse/shared';
import type { ActivityDefinition } from '@lifeverse/shared';

export const youngAdultActivities: ActivityDefinition[] = [
  {
    id: 'ya_deep_study',
    label: 'Deep Study Session',
    description: 'Library, coffee, no distractions. You are building knowledge that will compound for decades.',
    domain: 'academic',
    timeCost: 2,
    mentalCost: 25,
    burnoutRisk: 0.1,
    statDeltas: [{ stat: 'intelligence', amount: 7 }, { stat: 'discipline', amount: 4 }],
    domainGains: [{ domain: 'academic', amount: 8 }],
    stages: [LifeStage.YoungAdult],
    weight: 2,
    tags: ['cognitive', 'high-effort'],
  },
  {
    id: 'ya_professional_networking',
    label: 'Professional Networking',
    description: 'Industry events, LinkedIn, cold coffees. Building the network before you need it.',
    domain: 'career',
    secondaryDomain: 'social',
    timeCost: 1,
    mentalCost: 10,
    statDeltas: [{ stat: 'charisma', amount: 4 }],
    domainGains: [{ domain: 'career', amount: 5 }, { domain: 'social', amount: 4 }],
    stages: [LifeStage.YoungAdult],
    weight: 2,
    tags: ['career', 'social'],
  },
  {
    id: 'ya_gym',
    label: 'Gym and Fitness',
    description: 'Consistent training. Your metabolism is at its peak — use it.',
    domain: 'physical',
    timeCost: 1,
    physicalCost: 20,
    statDeltas: [{ stat: 'health', amount: 5 }, { stat: 'discipline', amount: 3 }],
    domainGains: [{ domain: 'physical', amount: 7 }],
    stages: [LifeStage.YoungAdult],
    weight: 2,
    tags: ['health', 'discipline'],
  },
  {
    id: 'ya_social_life',
    label: 'Active Social Life',
    description: 'Friends, dates, events, bars, concerts. Being young is practice for being human.',
    domain: 'social',
    timeCost: 1,
    statDeltas: [{ stat: 'charisma', amount: 3 }, { stat: 'happiness', amount: 4 }],
    domainGains: [{ domain: 'social', amount: 6 }],
    stages: [LifeStage.YoungAdult],
    weight: 2,
    tags: ['social', 'fun'],
  },
  {
    id: 'ya_creative_pursuit',
    label: 'Creative Pursuit',
    description: 'Your creative outlet — pursued with intent, not just as a hobby.',
    domain: 'creative',
    timeCost: 2,
    mentalCost: 20,
    statDeltas: [{ stat: 'creativity', amount: 7 }],
    domainGains: [{ domain: 'creative', amount: 8 }],
    stages: [LifeStage.YoungAdult],
    weight: 1,
    tags: ['creative'],
  },
  {
    id: 'ya_side_hustle',
    label: 'Side Hustle',
    description: 'Build something on the side. Not for the money — for the proof that you can.',
    domain: 'career',
    secondaryDomain: 'creative',
    timeCost: 2,
    mentalCost: 20,
    burnoutRisk: 0.2,
    statDeltas: [{ stat: 'discipline', amount: 5 }],
    domainGains: [{ domain: 'career', amount: 6 }, { domain: 'creative', amount: 5 }],
    stages: [LifeStage.YoungAdult],
    minDomainLevel: { career: 15, creative: 20 },
    weight: 1,
    tags: ['career', 'creative', 'high-effort'],
  },
  {
    id: 'ya_therapy',
    label: 'Therapy or Journaling',
    description: 'Sit with yourself. Sort out what your childhood packed into your luggage.',
    domain: 'mental',
    timeCost: 1,
    moneyCost: 800,
    statDeltas: [{ stat: 'happiness', amount: 4 }],
    domainGains: [{ domain: 'mental', amount: 7 }],
    energyRestore: { mental: 30 },
    statDeltasOverride: [{ stat: 'stress', amount: -8 }],
    stages: [LifeStage.YoungAdult],
    weight: 1,
    tags: ['mental', 'recovery'],
  },
  {
    id: 'ya_travel',
    label: 'Travel and Explore',
    description: 'A month abroad, a road trip, a one-way ticket somewhere unfamiliar.',
    domain: 'social',
    secondaryDomain: 'creative',
    timeCost: 2,
    moneyCost: 3000,
    statDeltas: [{ stat: 'charisma', amount: 5 }, { stat: 'creativity', amount: 5 }, { stat: 'happiness', amount: 7 }],
    domainGains: [{ domain: 'social', amount: 5 }, { domain: 'creative', amount: 4 }],
    stages: [LifeStage.YoungAdult],
    weight: 1,
    tags: ['social', 'creative', 'expensive'],
  },
  {
    id: 'ya_upskill_course',
    label: 'Upskill with a Course',
    description: 'Certifications, online bootcamps, language classes. Structured learning beyond university.',
    domain: 'academic',
    secondaryDomain: 'career',
    timeCost: 1,
    mentalCost: 15,
    moneyCost: 500,
    statDeltas: [{ stat: 'intelligence', amount: 4 }],
    domainGains: [{ domain: 'academic', amount: 5 }, { domain: 'career', amount: 5 }],
    stages: [LifeStage.YoungAdult],
    weight: 2,
    tags: ['cognitive', 'career'],
  },
  {
    id: 'ya_rest',
    label: 'Rest and Recovery',
    description: 'Nothing scheduled. No guilt. This is maintenance, not laziness.',
    domain: 'mental',
    timeCost: 1,
    statDeltas: [{ stat: 'happiness', amount: 3 }],
    domainGains: [{ domain: 'mental', amount: 5 }],
    energyRestore: { mental: 30, physical: 25 },
    stages: [LifeStage.YoungAdult],
    weight: 1,
    tags: ['rest', 'recovery'],
  },
  {
    id: 'ya_mentor_relationship',
    label: 'Pursue a Mentorship',
    description: 'Find someone ten years ahead of you and ask the hard questions.',
    domain: 'social',
    timeCost: 1,
    statDeltas: [{ stat: 'charisma', amount: 4 }, { stat: 'intelligence', amount: 3 }],
    domainGains: [{ domain: 'social', amount: 5 }, { domain: 'career', amount: 4 }],
    stages: [LifeStage.YoungAdult],
    requiredFlags: ['hasMentor'],
    weight: 1,
    tags: ['social', 'career'],
  },
  {
    id: 'ya_launch_project',
    label: 'Launch a Real Project',
    description: 'Publish it. Ship it. Put something real into the world and deal with what happens.',
    domain: 'creative',
    secondaryDomain: 'career',
    timeCost: 2,
    mentalCost: 25,
    physicalCost: 10,
    burnoutRisk: 0.25,
    statDeltas: [{ stat: 'creativity', amount: 6 }, { stat: 'discipline', amount: 6 }],
    domainGains: [{ domain: 'creative', amount: 8 }, { domain: 'career', amount: 6 }],
    stages: [LifeStage.YoungAdult],
    minDomainLevel: { creative: 30, career: 20 },
    weight: 1,
    tags: ['creative', 'career', 'high-effort'],
  },
];
